"""boundaries.py [--out FILE] [--self-test] [--psyq-dir DIR] -- forced function/object boundaries per program (T8.c1).

Programs: SLUS_013.95 (text 0x80010000..0x8008F000, exeproof.load_image) + every `code` row of config/loadmap.txt
(rock/NN.bin at its base, sha1 = manifest, via loadmap.load_members). Ghidra side: config/ghidra/<prog>.jsonl.
Rows (addresses "0x%08x", spans [lo, hi) with hi exclusive):
  jtbl <table_lo> <table_hi> <func> <src> [note]
    scan: every `jr X` (X != ra) in the program's code range whose X comes from `lw X,off(B)`, B from `addu B,P,Q`
    with exactly one of P/Q a lui(+addiu/ori) constant C and the other `sll I,J,2`; table = C + off (covers both gcc
    forms: lui/addiu/addu/lw 0 and lui at/addu at/lw %lo(at)). Extent: `sltiu _,J,N` (J not redefined before the
    sll) -> N words, else consecutive words pointing into the program's code range. The table must lie in the
    image and not contain the dispatch. Defs are looked up backwards within WINDOW instructions.
    ghidra: `switchdataD_*` labels, entry count from the "Address table[N] created" bookmark at the same address.
    src both|scan|ghidra; func = the Ghidra func start at or before the jr (`-` if none; ghidra-only: the label's
    reference is unknown, `-`). Disagreements carry a reason computed below (reasons_scan / reasons_ghidra); a hi
    mismatch on a `both` row is noted `ghidra_hi=0x..`. A one-sided row with no reason -> rc 1.
  lib <lo> <hi> <LIB/OBJ>: a Ghidra func (name or a single-candidate "Possible X.OBJ/name" plate) whose name is a
    label of a PsyQ signature object (<psyq-dir>/<ver>/*.json, ver from the export's `psyqNNN` archive) and whose
    signature (?? = wildcard) matches the image at lo = func - label offset; hi = lo + sig length. Emitted only
    when exactly one (lib, obj, lo) verifies; ambiguous ones are counted in the header.
  optcand <lo> <hi> <reason> funcs=<n>: contiguous Ghidra funcs (bodies = [start, next func/data start)) whose
    first PROLOGUE instructions set fp from sp (`addu/or fp,sp,zero`): reason fp-frame+arg-spill when a0..a3 are
    also stored to fp-relative slots there, else fp-frame (-O0 shapes); a span's reason = its funcs' reasons joined.
  fstart <addr> calls=<n>: in-program `jal` targets, jal inside a Ghidra func body, target not a Ghidra func start;
    exe rows add ovl_calls=<n> (such jals from overlay func bodies into the exe text).
rc 0 ok; 1 unexplained disagreement or self-test failure; 2 bad inputs. --self-test runs the scan on synthetic
bytes (no game data). Stdlib only.
"""
import argparse
import glob
import json
import os
import re
import struct
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import exeproof  # noqa: E402
import loadmap  # noqa: E402

REPO = exeproof.REPO
GHIDRA = REPO / "config/ghidra"
LOADMAP = REPO / "config/loadmap.txt"
EXE_LO, EXE_HI = exeproof.CODE_LO, exeproof.CODE_END
WINDOW = 32  # instructions searched backwards for a def
PROLOGUE = 16  # instructions inspected for the -O0 frame shape
RA, SP, FP, AT = 31, 29, 30, 1
HEADER = "# generated by tools/mmx6/boundaries.py (make boundaries); do not edit"
KIND_ORDER = {"jtbl": 0, "lib": 1, "optcand": 2, "fstart": 3}


def h(a):
    return f"0x{a:08x}"


def s16(v):
    return v - 0x10000 if v & 0x8000 else v


def bad(msg):
    print(f"boundaries: {msg}", file=sys.stderr)
    sys.exit(2)


class Prog:
    def __init__(self, name, base, img, code_lo, code_hi):
        self.name, self.base, self.img, self.code_lo, self.code_hi = name, base, img, code_lo, code_hi

    def inimg(self, a, n=4):
        return self.base <= a and a + n <= self.base + len(self.img)

    def word(self, a):
        return struct.unpack_from("<I", self.img, a - self.base)[0]

    def dec(self, a):
        w = self.word(a)
        return w, w >> 26, (w >> 21) & 31, (w >> 16) & 31, (w >> 11) & 31, (w >> 6) & 31, w & 0xFFFF, w & 63


R_WRITERS = {0x00, 0x02, 0x03, 0x04, 0x06, 0x07, 0x09, 0x10, 0x12} | set(range(0x20, 0x2C))


def dest(d):
    """Register written by the decoded instruction, or None."""
    w, op, rs, rt, rd, sh, imm, fn = d
    if op == 0:
        return rd if fn in R_WRITERS and rd else None
    if op == 3:
        return RA
    if 0x08 <= op <= 0x0F or 0x20 <= op <= 0x26:
        return rt or None
    return None


def find_def(p, a, reg, lo=None):
    """Nearest instruction before `a` (within WINDOW, not below lo) writing reg -> (addr, decoded) or None."""
    stop = max(p.code_lo, a - 4 * WINDOW, lo if lo is not None else p.code_lo)
    for x in range(a - 4, stop - 1, -4):
        d = p.dec(x)
        if dest(d) == reg:
            return x, d
    return None


def eval_const(p, a, reg, depth=0):
    """Constant value of reg at `a` from lui[/addiu/ori] chains, else None."""
    if reg == 0:
        return 0
    if depth > 3:
        return None
    f = find_def(p, a, reg)
    if not f:
        return None
    x, (w, op, rs, rt, rd, sh, imm, fn) = f
    if op == 0x0F:
        return (imm << 16) & 0xFFFFFFFF
    if op in (0x09, 0x0D):
        c = eval_const(p, x, rs, depth + 1)
        if c is None:
            return None
        return (c + s16(imm)) & 0xFFFFFFFF if op == 0x09 else c | imm
    return None


def code_ptr(p, v):
    return v & 3 == 0 and p.code_lo <= v < p.code_hi


def scan_jr(p, j):
    """Dispatch at jr address j -> (table_lo, table_hi, bound) | ('reject', why, table_lo|None)."""
    w, op, rs, rt, rd, sh, imm, fn = p.dec(j)
    f = find_def(p, j, rs)
    if not f or f[1][1] != 0x23:
        return ("reject", "target-not-lw", None)
    la, (_, _, base, _, _, _, off, _) = f
    g = find_def(p, la, base)
    if not g or g[1][1] != 0 or g[1][7] != 0x21:
        return ("reject", "base-not-addu", None)
    aa, (_, _, r1, r2, _, _, _, _) = g
    c1, c2 = eval_const(p, aa, r1), eval_const(p, aa, r2)
    if (c1 is None) == (c2 is None):
        return ("reject", "no-unique-const-base", None)
    c, idx = (c1, r2) if c1 is not None else (c2, r1)
    tlo = (c + s16(off)) & 0xFFFFFFFF
    s = find_def(p, aa, idx)
    if not s or s[1][1] != 0 or s[1][7] != 0 or s[1][5] != 2:
        return ("reject", "index-not-sll2", tlo)
    sa, (_, _, _, jr_, _, _, _, _) = s
    pre = find_def(p, sa, jr_)
    n = None
    for x in range(sa - 4, max(p.code_lo, sa - 4 * WINDOW) - 1, -4):
        d = p.dec(x)
        if d[1] == 0x0B and d[2] == jr_ and (pre is None or pre[0] <= x):
            n = d[6]
            break
    if not p.inimg(tlo):
        return ("reject", "table-outside-image", tlo)
    if n is None:
        n = 0
        while p.inimg(tlo + 4 * n) and code_ptr(p, p.word(tlo + 4 * n)) and n < 4096:
            n += 1
        bound = "words"
    else:
        bound = "sltiu"
    thi = tlo + 4 * n
    if n == 0 or not p.inimg(tlo, 4 * n):
        return ("reject", "table-outside-image", tlo)
    if tlo <= j < thi:
        return ("reject", "table-covers-dispatch", tlo)
    return (tlo, thi, bound)


def scan(p):
    """-> (hits {table_lo: [(jr, thi, bound)]}, rejects [(jr, why, tlo)])"""
    hits, rejects = {}, []
    for j in range(p.code_lo, p.code_hi, 4):
        if not p.inimg(j):
            break
        d = p.dec(j)
        if d[1] != 0 or d[7] != 0x08 or d[2] == RA:
            continue
        r = scan_jr(p, j)
        if r[0] == "reject":
            rejects.append((j, r[1], r[2]))
        else:
            hits.setdefault(r[0], []).append((j, r[1], r[2]))
    return hits, rejects


def load_ghidra(name):
    path = GHIDRA / f"{name}.jsonl"
    if not path.is_file():
        bad(f"missing {path}")
    recs = [json.loads(line) for line in path.read_text().splitlines() if line]
    return recs


def ghidra_view(p, recs):
    v = {"funcs": {}, "data": [], "labels": {}, "abook": {}, "plates": {}, "archive": None}
    for r in recs:
        k = r["k"]
        if k == "archive":
            v["archive"] = r["name"]
            continue
        if "addr" not in r:
            continue
        a = int(r["addr"], 16)
        if not p.inimg(a, 1):
            continue
        if k == "func":
            v["funcs"][a] = r["name"]
        elif k == "data":
            v["data"].append((a, a + max(1, r.get("len", 1))))
        elif k == "label":
            v["labels"].setdefault(a, []).append(r["name"])
        elif k == "bookmark" and r.get("cat") == "Address Table":
            m = re.match(r"Address table\[(\d+)\]", r.get("text", ""))
            if m:
                v["abook"][a] = int(m.group(1))
        elif k == "comment" and r.get("type") == "plate":
            v["plates"][a] = r["text"]
    v["switch"] = {a: v["abook"].get(a) for a, ns in v["labels"].items() if any(n.startswith("switchdata") for n in ns)}
    starts = sorted(set(v["funcs"]) | {lo for lo, _ in v["data"]})
    end = p.base + len(p.img)
    nxt = {a: (starts[i + 1] if i + 1 < len(starts) else end) for i, a in enumerate(starts)}
    v["bodies"] = sorted((a, nxt[a]) for a in v["funcs"])
    v["fstarts"] = sorted(v["funcs"])
    return v


def func_at(v, a):
    best = None
    for s in v["fstarts"]:
        if s > a:
            break
        best = s
    return best


def in_body(v, a):
    for lo, hi in v["bodies"]:
        if lo <= a < hi:
            return lo
    return None


def in_data(v, a):
    return any(lo <= a < hi for lo, hi in v["data"])


def reason_scan(p, v, j, tlo):
    """Why Ghidra has no switchdata label at a table our scan found (first matching category)."""
    if in_data(v, j):
        return "jr-in-ghidra-data"
    if func_at(v, j) is None:
        return "jr-before-first-ghidra-func"
    if in_body(v, j) is None:
        return "jr-outside-ghidra-func-body"
    if any(t < tlo < t + 4 * n for t, n in v["switch"].items() if n):
        return "inside-ghidra-switch-extent"
    if tlo in v["abook"]:
        return "ghidra-address-table-not-switch"
    if tlo in v["labels"]:
        return "ghidra-other-label"
    if in_data(v, tlo):
        return "table-in-ghidra-typed-data"
    return None


def hilo_refs(p, tlo):
    """Code addresses of lui %hi(tlo) followed (within WINDOW, same reg) by addiu/lw/ori-free %lo(tlo) use."""
    hi, lo = ((tlo + 0x8000) >> 16) & 0xFFFF, tlo & 0xFFFF
    out = []
    for a in range(p.code_lo, p.code_hi, 4):
        if not p.inimg(a):
            break
        d = p.dec(a)
        if d[1] != 0x0F or d[6] != hi:
            continue
        for x in range(a + 4, min(p.code_hi, a + 4 * WINDOW), 4):
            if not p.inimg(x):
                break
            e = p.dec(x)
            if e[1] in (0x09, 0x23) and e[2] == d[3] and e[6] == lo:
                out.append(a)
                break
    return out


def reason_ghidra(p, v, tlo, rejects, hits):
    rj = [why for (_, why, t) in rejects if t == tlo]
    if rj:
        return "scan-rejected:" + "+".join(sorted(set(rj)))
    if any(t < tlo < thi for t, xs in hits.items() for _, thi, _ in xs):
        return "label-inside-scan-table"
    if any(t < tlo < t + 4 * n for t, n in v["switch"].items() if n):
        return "label-inside-ghidra-table"
    if not hilo_refs(p, tlo):
        return "no-hi-lo-ref-in-code"
    return "hi-lo-ref-without-jr-dispatch"


# ---- PsyQ signatures ----
def load_sigs(psyq_dir, archive):
    if not psyq_dir or not archive:
        return {}
    m = re.fullmatch(r"psyq(\d+)", archive)
    if not m:
        return {}
    d = os.path.join(psyq_dir, m.group(1))
    files = sorted(glob.glob(os.path.join(d, "*.json")))
    if not files:
        bad(f"no PsyQ signature files in {d}")
    by_label = {}
    for fpath in files:
        lib = os.path.basename(fpath)[:-5]
        for obj in json.load(open(fpath)):
            if "sig" not in obj:  # xbss-only objects carry no code
                continue
            toks = obj["sig"].split()
            pat = [None if t == "??" else int(t, 16) for t in toks]
            for lab in obj.get("labels", []):
                by_label.setdefault(lab["name"], []).append((f"{lib}/{obj['name']}", lab["offset"], pat))
    return by_label


def sig_ok(p, lo, pat):
    if not p.inimg(lo, len(pat)):
        return False
    b = p.img[lo - p.base:lo - p.base + len(pat)]
    return all(x is None or x == y for x, y in zip(pat, b))


def lib_rows(p, v, by_label):
    found, amb, plate_amb = {}, 0, 0
    cands = []
    for a, name in sorted(v["funcs"].items()):
        if name in by_label:
            cands.append((a, [name], None))
    for a, text in sorted(v["plates"].items()):
        alts = re.findall(r"Possible ([^/\n]+)/(\S+)", text)
        if not alts:
            continue
        if len(alts) > 1:
            plate_amb += 1
            continue
        cands.append((a, [alts[0][1]], alts[0][0].upper()))
    for a, names, objname in cands:
        ok = set()
        for nm in names:
            for lname, off, pat in by_label.get(nm, []):
                if objname and not lname.endswith("/" + objname):
                    continue
                lo = a - off
                if sig_ok(p, lo, pat):
                    ok.add((lo, lo + len(pat), lname))
        if len(ok) == 1:
            (lo, hi, lname), = ok
            found[(lo, hi, lname)] = 1
        elif len(ok) > 1:
            amb += 1
    spans = Counter((lo, hi) for lo, hi, _ in found)
    dup = {s for s, c in spans.items() if c > 1}  # one span verified under two names (e.g. LIBCD/LIBDS twins)
    amb += sum(spans[s] for s in dup)
    rows = sorted(r for r in found if (r[0], r[1]) not in dup)
    covered = sum(1 for f in v["fstarts"] if any(lo <= f < hi for lo, hi, _ in rows))
    return rows, amb, plate_amb, covered


# ---- -O0 candidates ----
def frame_shape(p, lo, hi):
    fp = spill = False
    for a in range(lo, min(hi, lo + 4 * PROLOGUE), 4):
        if not p.inimg(a):
            break
        w, op, rs, rt, rd, sh, imm, fn = p.dec(a)
        if op == 0 and fn in (0x21, 0x25) and rd == FP and {rs, rt} == {SP, 0}:
            fp = True
        elif fp and op == 0x2B and rs == FP and 4 <= rt <= 7:
            spill = True
    return None if not fp else "fp-frame+arg-spill" if spill else "fp-frame"


def optcand_rows(p, v):
    rows, cur = [], None
    for lo, hi in v["bodies"]:
        r = frame_shape(p, lo, hi)
        if r is None:
            if cur:
                rows.append(cur)
            cur = None
        elif cur and cur[1] == lo:
            cur = (cur[0], hi, cur[2] | {r}, cur[3] + 1)
        else:
            if cur:
                rows.append(cur)
            cur = (lo, hi, {r}, 1)
    if cur:
        rows.append(cur)
    return [(lo, hi, "|".join(sorted(rs)), n) for lo, hi, rs, n in rows]


def jal_misses(p, v, starts, tlo, thi):
    """Counter of jal targets in [tlo, thi) not in starts, from jals inside p's Ghidra func bodies."""
    calls = Counter()
    for lo, hi in v["bodies"]:
        for a in range(lo, hi, 4):
            if not p.inimg(a):
                break
            w = p.word(a)
            if w >> 26 != 3:
                continue
            t = (a & 0xF0000000) | ((w & 0x3FFFFFF) << 2)
            if tlo <= t < thi and t not in starts:
                calls[t] += 1
    return calls


def fstart_rows(p, v, extern=None):
    """In-program jal targets that are not func starts; extern = Counter of overlay jals into this text."""
    calls = jal_misses(p, v, set(v["fstarts"]), p.code_lo, p.code_hi)
    if extern is None:
        return sorted(calls.items())
    return [(t, calls[t], extern[t]) for t in sorted(set(calls) | set(extern))]


# ---- per program ----
def boundaries(p, v, psyq_dir, extern=None):
    hits, rejects = scan(p)
    rows, unexplained = [], 0
    cnt = Counter()
    for tlo in sorted(set(hits) | set(v["switch"])):
        gh = v["switch"].get(tlo, "absent") if tlo in v["switch"] else "absent"
        if tlo in hits:
            for j, thi, bound in sorted(hits[tlo]):
                fs = func_at(v, j)
                fn = h(fs) if fs is not None else "-"
                if tlo in v["switch"]:
                    note = ""
                    if gh is None:
                        note = " ghidra_hi=unknown"
                    elif tlo + 4 * gh != thi:
                        note = f" ghidra_hi={h(tlo + 4 * gh)}"
                        cnt["hi_mismatch"] += 1
                    rows.append(("jtbl", tlo, f"jtbl {h(tlo)} {h(thi)} {fn} both{note}"))
                    cnt["both"] += 1
                else:
                    why = reason_scan(p, v, j, tlo)
                    if why is None:
                        unexplained += 1
                        why = "UNEXPLAINED"
                    cnt["scan"] += 1
                    cnt["r:" + why] += 1
                    rows.append(("jtbl", tlo, f"jtbl {h(tlo)} {h(thi)} {fn} scan {why} bound={bound}"))
        else:
            n = v["switch"][tlo]
            thi = h(tlo + 4 * n) if n is not None else "unknown"
            why = reason_ghidra(p, v, tlo, rejects, hits)
            cnt["ghidra"] += 1
            cnt["r:" + why] += 1
            rows.append(("jtbl", tlo, f"jtbl {h(tlo)} {thi} - ghidra {why}"))
    sites = sum(len(x) for x in hits.values())
    by_label = load_sigs(psyq_dir, v["archive"]) if psyq_dir else {}
    libs, amb, plate_amb, covered = lib_rows(p, v, by_label)
    for lo, hi, name in libs:
        rows.append(("lib", lo, f"lib {h(lo)} {h(hi)} {name}"))
    overl = sum(1 for i in range(1, len(libs)) if libs[i][0] < libs[i - 1][1])
    opts = optcand_rows(p, v)
    for lo, hi, why, n in opts:
        rows.append(("optcand", lo, f"optcand {h(lo)} {h(hi)} {why} funcs={n}"))
    ofuncs = sum(n for *_, n in opts)
    fst = fstart_rows(p, v, extern)
    for a, n, *m in fst:
        ovl = f" ovl_calls={m[0]}" if m else ""
        rows.append(("fstart", a, f"fstart {h(a)} calls={n}{ovl}"))
    rows.sort(key=lambda r: (KIND_ORDER[r[0]], r[1], r[2]))
    nf = len(v["fstarts"])
    head = [f"# program {p.name} base {h(p.base)} size 0x{len(p.img):x}",
            f"# jtbl sites={sites} switchdata={len(v['switch'])} both={cnt['both']} scan={cnt['scan']} "
            f"ghidra={cnt['ghidra']} hi_mismatch={cnt['hi_mismatch']} rejected_jr={len(rejects)}",
            f"# lib objects={len(libs)} funcs_covered={covered}/{nf} ambiguous_name={amb} ambiguous_plate={plate_amb} "
            f"overlaps={overl}",
            f"# optcand spans={len(opts)} funcs={ofuncs}/{nf} fstart={len(fst)}"]
    reasons = Counter({k[2:]: c for k, c in cnt.items() if k.startswith("r:")})
    stats = dict(sites=sites, switch=len(v["switch"]), both=cnt["both"], scan=cnt["scan"], ghidra=cnt["ghidra"],
                 hi=cnt["hi_mismatch"], libs=len(libs), covered=covered, funcs=nf, ofuncs=ofuncs, fstart=len(fst),
                 amb=amb, pamb=plate_amb)
    return head + [r[2] for r in rows], unexplained, reasons, stats


def programs():
    img = exeproof.load_image()
    out = [Prog("SLUS_013.95", EXE_LO, img, EXE_LO, EXE_HI)]
    mems = loadmap.load_members()
    for line in LOADMAP.read_text().splitlines():
        f = line.split()
        if not f or f[0].startswith("#") or f[0] == "exe" or len(f) < 3 or f[2] != "code":
            continue
        k, base = int(f[0]), int(f[1], 16)
        m = mems[k]
        out.append(Prog(f"rock_{k:02d}", base, m, base, base + len(m)))
    return out


# ---- self-test (synthetic bytes) ----
def enc_r(rs, rt, rd, sh, fn):
    return (rs << 21) | (rt << 16) | (rd << 11) | (sh << 6) | fn


def enc_i(op, rs, rt, imm):
    return (op << 26) | (rs << 21) | (rt << 16) | (imm & 0xFFFF)


def self_test():
    base = 0x80010000
    V0, A0, A1, T0, T1, T9, ZERO = 2, 4, 5, 8, 9, 25, 0
    NOP, JR_RA = 0, 0x03E00008
    code = []
    t1, t2 = base + 0x200, base + 0x240  # tables in data after the code

    def hi(x):
        return ((x + 0x8000) >> 16) & 0xFFFF

    # f1 (form A, bounded by sltiu 5): table t1
    f1 = base + 4 * len(code)
    code += [enc_i(0x09, SP, SP, -24), enc_i(0x0B, A0, V0, 5), enc_i(0x04, V0, 0, 8), enc_r(0, A0, V0, 2, 0),
             enc_i(0x0F, 0, AT, hi(t1)), enc_i(0x09, AT, AT, t1), enc_r(V0, AT, V0, 0, 0x21), enc_i(0x23, V0, V0, 0),
             NOP, enc_r(V0, 0, 0, 0, 8), NOP]
    j1 = base + 4 * (len(code) - 2)
    cases = base + 4 * len(code)
    code += [JR_RA, NOP] * 3
    # f2 (form B, unbounded: extent = consecutive code pointers): table t2
    code += [enc_r(0, A1, T0, 2, 0), enc_i(0x0F, 0, AT, hi(t2)), enc_r(AT, T0, AT, 0, 0x21), enc_i(0x23, AT, T1, t2),
             NOP, enc_r(T1, 0, 0, 0, 8), NOP]
    j2 = base + 4 * (len(code) - 2)
    # non-tables: lw t9,0(a0); jr t9 -- and jr v0 with no lui base (move v0,a0)
    code += [enc_i(0x23, A0, T9, 0), NOP, enc_r(T9, 0, 0, 0, 8), NOP,
             enc_r(A0, ZERO, V0, 0, 0x21), enc_r(V0, 0, 0, 0, 8), NOP]
    # -O0 shape: addiu sp; sw fp; move fp,sp; sw a0,24(fp)
    f3 = base + 4 * len(code)
    code += [enc_i(0x09, SP, SP, -8), enc_i(0x2B, SP, FP, 0), enc_r(SP, 0, FP, 0, 0x21), enc_i(0x2B, FP, A0, 24),
             JR_RA, NOP]
    f4 = base + 4 * len(code)
    code += [(3 << 26) | ((cases & 0x0FFFFFFF) >> 2), NOP, JR_RA, NOP]  # jal into f1's case code (not a start)
    img = bytearray(0x280)
    for i, w in enumerate(code):
        struct.pack_into("<I", img, 4 * i, w)
    for i in range(5):
        struct.pack_into("<I", img, t1 - base + 4 * i, cases + 8 * (i % 3))
    for i in range(3):
        struct.pack_into("<I", img, t2 - base + 4 * i, cases + 8 * i)
    p = Prog("synthetic", base, bytes(img), base, base + 4 * len(code))
    hits, rejects = scan(p)
    v = {"fstarts": [f1, f3, f4], "bodies": [(f1, f3), (f3, f4), (f4, f4 + 16)]}
    checks = [
        ("form A found exact", hits.get(t1) == [(j1, t1 + 20, "sltiu")]),
        ("form B found exact", hits.get(t2) == [(j2, t2 + 12, "words")]),
        ("only the two tables", sorted(hits) == [t1, t2]),
        ("lw t9,0(a0); jr t9 rejected", any(w == "base-not-addu" for _, w, _ in rejects)),
        ("jr v0 without lui base rejected", any(w == "target-not-lw" for _, w, _ in rejects)),
        ("optcand fp-frame+arg-spill", optcand_rows(p, v) == [(f3, f4, "fp-frame+arg-spill", 1)]),
        ("fstart jal target", fstart_rows(p, v) == [(cases, 1)]),
    ]
    fails = [n for n, ok in checks if not ok]
    for n in fails:
        print(f"SELF-TEST FAIL {n}")
    if fails:
        return 1
    print(f"SELF-TEST PASS {len(checks)}")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--psyq-dir")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    if a.psyq_dir and not os.path.isdir(a.psyq_dir):
        bad(f"--psyq-dir {a.psyq_dir} is not a directory")
    lines = [HEADER, "# rows: jtbl <table_lo> <table_hi> <func> <src> [note|reason]; lib <lo> <hi> <LIB/OBJ>; "
             "optcand <lo> <hi> <reason> funcs=<n>; fstart <addr> calls=<n> [ovl_calls=<n>]; spans [lo, hi)"]
    total_unexpl, reasons, tot = 0, Counter(), Counter()
    progs = programs()
    views = [ghidra_view(p, load_ghidra(p.name)) for p in progs]
    exe, ev = progs[0], views[0]
    extern = Counter()  # overlay jals into the exe text that miss an exe func start
    for p, v in zip(progs[1:], views[1:]):
        extern += jal_misses(p, v, set(ev["fstarts"]), exe.code_lo, exe.code_hi)
    for i, (p, v) in enumerate(zip(progs, views)):
        body, unexpl, rs, st = boundaries(p, v, a.psyq_dir, extern if i == 0 else None)
        lines += body
        total_unexpl += unexpl
        reasons += rs
        tot.update(st)
    lines.append(f"# totals programs={len(progs)} sites={tot['sites']} switchdata={tot['switch']} both={tot['both']} "
                 f"scan={tot['scan']} ghidra={tot['ghidra']} hi_mismatch={tot['hi']} lib={tot['libs']} "
                 f"lib_funcs={tot['covered']}/{tot['funcs']} optcand_funcs={tot['ofuncs']}/{tot['funcs']} "
                 f"fstart={tot['fstart']} unexplained={total_unexpl}")
    lines.append("# reasons " + " ".join(f"{k}={c}" for k, c in sorted(reasons.items())))
    text = "\n".join(lines) + "\n"
    if a.out:
        Path(a.out).write_text(text)
    else:
        sys.stdout.write(text)
    print(lines[-2], file=sys.stderr)
    print(lines[-1], file=sys.stderr)
    return 1 if total_unexpl else 0


if __name__ == "__main__":
    sys.exit(main())
