#!/usr/bin/env python3
"""carve.py -- deliberate segment edges per binary: jump-table rodata carves and opt-level unit splits (stdlib only).

    carve.py jtbl <prog> <table_lo>                         exe only; table = config/boundaries.txt `jtbl` row lo
    carve.py opt <prog> <tu> <split vram> [--cflags "<f>"]  split <tu> at a corpus function start
    carve.py --check                                        every record still valid (fail-closed)
    carve.py --self-test                                    planted refusals on a scratch copy under .run/

Record config/carve.<prog>.txt (tracked, written only here): `jtbl <table_lo> <tu>` | `opt <tu> <vram> <newtu>
[cflags...]`, newtu = vram hex without 0x80. tools/mmx6/segment.py applies it to the generated yaml block: an opt row
is a text edge (TU <newtu>, kind of its parent); a jtbl row cuts the exe rodata block at [lo, hi) into `.rodata <tu>`,
which splat pairs with unit <tu> (the table migrates into its dispatcher's INCLUDE_ASM .s). On a c parent, opt moves the
tail of src/<prog>/<tu>.c (from the split function's chunk) to src/<prog>/<newtu>.c and adds `<prog> <newtu>` to
config/c_units.txt. config/carve.<prog>.mk (generated from the record, included by the Makefile) sets the per-unit
cc1 flags `CFLAGS_<newtu>`. Inputs: build/corpus/functions.jsonl (corpus.py --all) for function starts and TUs.
Prints `CARVE jtbl OK <prog> 0x<lo>` / `CARVE opt OK <prog> <tu>@0x<vram>`; --check prints those per verified row and
ends `CARVE CHECK OK <n> carves`; --self-test ends `CARVE CONTROL OK`. A refusal prints `CARVE REFUSE <code> ...`, rc 1.
"""
import json
import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import segment  # noqa: E402

CORPUS = os.path.join(ROOT, "build", "corpus", "functions.jsonl")
SCRATCH = os.path.join(ROOT, ".run", "carve-selftest")
INC_RE = re.compile(r"^INCLUDE_ASM\(\"[^\"]*\", *(\w+)\);")
CDEF_RE = re.compile(r"(?!INCLUDE_ASM\b)[A-Za-z_][^;{}()#]*?\b([A-Za-z_]\w*)\s*\([^;{}]*?\)\s*\{(\s*\})?")
CINC_RE = re.compile(r"^#include \"([^\"]+\.c)\"[ \t]*$")


class Refuse(Exception):
    pass


def refuse(code, msg):
    raise Refuse("CARVE REFUSE %s %s" % (code, msg))


def use_root(root):
    """Point segment.py's inputs at root (the repo, or the self-test scratch copy)."""
    segment.ROOT = root
    segment.BOUNDARIES = os.path.join(root, "config", "boundaries.txt")
    segment.C_UNITS = os.path.join(root, "config", "c_units.txt")


def cfg(root, *p):
    return os.path.join(root, "config", *p)


# ---- inputs --------------------------------------------------------------------------------------------------------

def jtbl_rows(prog):
    """{lo: (hi, func, src, note)} of prog's boundaries.txt jtbl rows (func None for `-`)."""
    out, cur = {}, None
    with open(segment.BOUNDARIES) as f:
        for line in f:
            w = line.split()
            if line.startswith("# program "):
                cur = w[2]
            elif cur == prog and len(w) >= 5 and w[0] == "jtbl":
                out[int(w[1], 16)] = (int(w[2], 16), None if w[3] == "-" else int(w[3], 16), w[4], " ".join(w[5:]))
    return out


def corpus(prog):
    """{vram: (name, tu)} of prog's corpus functions."""
    if not os.path.exists(CORPUS):
        refuse("no-corpus", "%s missing (run corpus.py --all after the build)" % CORPUS)
    out = {}
    with open(CORPUS) as f:
        for line in f:
            r = json.loads(line)
            if r["prog"] == prog:
                out[int(r["vram"], 16)] = (r["name"], r["tu"])
    return out


def read_record(root, prog):
    """[[kind, ...fields]] rows of config/carve.<prog>.txt, comments dropped."""
    path = cfg(root, "carve.%s.txt" % prog)
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return [w for w in (l.split("#", 1)[0].split() for l in f) if w]


def write_record(root, prog, rows):
    with open(cfg(root, "carve.%s.txt" % prog), "w") as f:
        f.write("# config/carve.%s.txt -- carves of %s, written only by tools/mmx6/carve.py (config/segmentation.md).\n"
                "# jtbl <table_lo> <tu> | opt <tu> <vram> <newtu> [cflags...]\n" % (prog, prog))
        f.writelines(" ".join(r) + "\n" for r in rows)


def render_mk(prog, rows):
    out = ["# config/carve.%s.mk -- generated by tools/mmx6/carve.py from config/carve.%s.txt; included by the "
           "Makefile.\n" % (prog, prog)]
    out += ["build/src/%s/%s.c.o: CFLAGS_%s := %s\n" % (prog, r[3], r[3], " ".join(r[4:]))
            for r in rows if r[0] == "opt" and len(r) > 4]
    return "".join(out)


def text_tus(prog):
    """[(vram, name)] text TUs of prog's generated block (carves applied)."""
    progs = segment.read_programs(segment.BOUNDARIES)
    out = []
    for l in segment.block(prog, progs)[1:-1]:
        w = l.strip()[3:-1].split(", ")
        if len(w) == 3 and w[1] in ("asm", "c"):
            out.append((int(w[0], 16), w[2]))
    base = progs[prog][0]
    off = (lambda o: o - segment.EXE["header"] + base) if prog == segment.EXE["name"] else (lambda o: o + base)
    return [(off(o), n) for o, n in out]


def regenerate(root, prog, rows):
    """Record, .mk and yaml block of prog from rows."""
    write_record(root, prog, rows)
    with open(cfg(root, "carve.%s.mk" % prog), "w") as f:
        f.write(render_mk(prog, rows))
    out = segment.block(prog, segment.read_programs(segment.BOUNDARIES))
    if segment.splice(cfg(root, prog + ".yaml"), out):
        refuse("yaml", "%s has no single BEGIN/END block" % cfg(root, prog + ".yaml"))


# ---- jtbl ----------------------------------------------------------------------------------------------------------

def carve_jtbl(root, prog, lo):
    rows = jtbl_rows(prog)
    if lo not in rows:
        refuse("not-a-row", "%s 0x%08X is not a jtbl row lo of config/boundaries.txt" % (prog, lo))
    hi, func, _, note = rows[lo]
    if func is None or "label-inside-scan-table" in note:
        refuse("no-dispatcher", "%s 0x%08X row has func `-` or note label-inside-scan-table" % (prog, lo))
    if prog != segment.EXE["name"]:
        refuse("no-rodata-block", "%s has no rodata block (overlays are one text span)" % prog)
    rec = read_record(root, prog)
    _, jt = segment.read_carves(prog)
    carved = segment.carved_rodata(prog, jt)
    for clo, chi, ctu in carved:
        if lo < chi and clo < hi:
            refuse("overlaps-carve", "%s [0x%08X,0x%08X) overlaps carved [0x%08X,0x%08X) %s" % (prog, lo, hi, clo, chi, ctu))
    pieces = segment.rodata_pieces(segment.EXE["rodata_lo"], segment.EXE["text_lo"], carved)
    ends = [p[0] for p in pieces[1:]] + [segment.EXE["text_lo"]]
    if not any(p[0] <= lo and hi <= e for p, e in zip(pieces, ends)):
        refuse("straddles", "%s [0x%08X,0x%08X) is not inside one rodata subsegment" % (prog, lo, hi))
    fn = corpus(prog).get(func)
    if fn is None:
        refuse("no-function", "%s dispatcher 0x%08X is not a corpus function start" % (prog, func))
    tu = fn[1]
    if tu not in segment.c_units(prog):
        refuse("not-c", "%s dispatcher 0x%08X is in asm TU %s (rodata pairs only with a c unit)" % (prog, func, tu))
    mine = [(a, b) for a, b, t in carved if t == tu]
    if mine and not any(hi == a or lo == b for a, b in mine):
        refuse("non-contiguous", "%s TU %s rodata would not be contiguous with 0x%08X" % (prog, tu, lo))
    regenerate(root, prog, rec + [["jtbl", "0x%08X" % lo, tu]])
    print("CARVE jtbl OK %s 0x%08X" % (prog, lo))


# ---- opt -----------------------------------------------------------------------------------------------------------

def anchors(lines, srcdir):
    """[(start, end, names)] of the function chunks of a C unit: INCLUDE_ASM lines, C definitions, and
    `#define ... #include "<body>.c" #undef ...` member blocks (names = the define targets, or the body's defs)."""
    out, i, text = [], 0, "\n".join(lines)
    offs = [0]
    for l in lines:
        offs.append(offs[-1] + len(l) + 1)
    while i < len(lines):
        l = lines[i]
        m = INC_RE.match(l)
        if m:
            out.append((i, i, {m.group(1)}))
            i += 1
            continue
        if l.startswith("#define ") or CINC_RE.match(l):
            j, names = i, set()
            while j < len(lines) and lines[j].startswith("#define "):
                names.update(lines[j].split()[2:3])
                j += 1
            m = CINC_RE.match(lines[j]) if j < len(lines) else None
            if m:
                if not names:
                    with open(os.path.join(srcdir, m.group(1))) as f:
                        names = {d.group(1) for d in (CDEF_RE.match(x) for x in f) if d}
                k = j + 1
                while k < len(lines) and lines[k].startswith("#undef "):
                    k += 1
                out.append((i, k - 1, names))
                i = k
                continue
        m = CDEF_RE.match(text, offs[i]) if l[:1].isalpha() and not l.startswith("extern") else None
        if m and "{" in text[offs[i]:m.end()]:
            e = i
            while offs[e + 1] <= m.end() - 1:
                e += 1
            if not m.group(2):
                while lines[e] != "}":
                    e += 1
            out.append((i, e, {m.group(1)}))
            i = e + 1
            continue
        i += 1
    return out


def split_c(path, newpath, name, tu, newtu):
    with open(path) as f:
        lines = f.read().rstrip("\n").split("\n")
    an = anchors(lines, os.path.dirname(path))
    k = [i for i, a in enumerate(an) if name in a[2]]
    if not k:
        refuse("no-chunk", "%s has no INCLUDE_ASM, C definition or member block of %s" % (path, name))
    if k[0] == 0:
        refuse("tu-start", "%s is the first chunk of %s" % (name, path))
    cut = an[k[0] - 1][1] + 1
    head = lines[:cut]
    while head and not head[-1].strip():
        head.pop()
    pre = lines[:an[0][0]]
    while pre and not pre[-1].strip():
        pre.pop()
    tail = lines[cut:]
    while tail and not tail[0].strip():
        tail.pop(0)
    old = "nonmatchings/%s\"" % tu
    tail = [l.replace(old, "nonmatchings/%s\"" % newtu) if INC_RE.match(l) else l for l in tail]
    with open(path, "w") as f:
        f.write("\n".join(head) + "\n")
    with open(newpath, "w") as f:
        f.write("\n".join(pre + [""] + tail) + "\n")


def carve_opt(root, prog, tu, vram, cflags):
    fns = corpus(prog)
    fn = fns.get(vram)
    if fn is None or fn[1] != tu:
        refuse("not-a-start", "%s 0x%08X is not a corpus function start inside TU %s" % (prog, vram, tu))
    start = dict((n, v) for v, n in text_tus(prog)).get(tu)
    if start is None:
        refuse("no-tu", "%s has no text TU %s" % (prog, tu))
    if vram == start:
        refuse("tu-start", "%s 0x%08X is the start of TU %s" % (prog, vram, tu))
    newtu = segment.hexname(vram)
    rec = read_record(root, prog)
    if tu in segment.c_units(prog):
        src = os.path.join(root, "src", prog)
        split_c(os.path.join(src, tu + ".c"), os.path.join(src, newtu + ".c"), fn[0], tu, newtu)
        with open(cfg(root, "c_units.txt"), "a") as f:
            f.write("%s %s\n" % (prog, newtu))
    for r in rec:  # a carved table whose dispatcher moves to the new TU follows it
        if r[0] == "jtbl":
            f = jtbl_rows(prog)[int(r[1], 16)][1]
            if r[2] == tu and f >= vram:
                r[2] = newtu
    regenerate(root, prog, rec + [["opt", tu, "0x%08X" % vram, newtu] + cflags.split()])
    print("CARVE opt OK %s %s@0x%08X" % (prog, tu, vram))


# ---- check ---------------------------------------------------------------------------------------------------------

def check(root, quiet=False):
    """Fail-closed: every record row valid against boundaries.txt + corpus, yaml block, .mk, c_units; count."""
    use_root(root)
    errs, n = [], 0
    say = (lambda s: None) if quiet else print
    progs = sorted(os.path.basename(p)[len("carve."):-len(".txt")] for p in os.listdir(cfg(root))
                   if p.startswith("carve.") and p.endswith(".txt"))
    mks = sorted(p[len("carve."):-len(".mk")] for p in os.listdir(cfg(root)) if p.startswith("carve.") and p.endswith(".mk"))
    errs += ["%s: config/carve.%s.mk without a record" % (p, p) for p in mks if p not in progs]
    for prog in progs:
        rec, fns, cset, rows = read_record(root, prog), corpus(prog), segment.c_units(prog), jtbl_rows(prog)
        for r in rec:
            if r[0] == "opt" and len(r) >= 4:
                fn = fns.get(int(r[2], 16))
                if fn is None or fn[1] != r[3] or r[3] != segment.hexname(int(r[2], 16)):
                    errs.append("%s opt %s %s: not a corpus function start of TU %s" % (prog, r[1], r[2], r[3]))
                elif r[1] in cset and r[3] not in cset:
                    errs.append("%s opt %s: c parent but no `%s %s` in config/c_units.txt" % (prog, r[3], prog, r[3]))
                else:
                    n += 1
                    say("CARVE opt OK %s %s@%s" % (prog, r[1], r[2]))
            elif r[0] == "jtbl" and len(r) == 3:
                row = rows.get(int(r[1], 16))
                fn = fns.get(row[1]) if row and row[1] is not None else None
                if row is None or "label-inside-scan-table" in row[3] or fn is None or fn[1] != r[2]:
                    errs.append("%s jtbl %s: row gone, no dispatcher, or dispatcher not in TU %s" % (prog, r[1], r[2]))
                else:
                    n += 1
                    say("CARVE jtbl OK %s %s" % (prog, r[1]))
            else:
                errs.append("%s: malformed record row %s" % (prog, " ".join(r)))
        mk = cfg(root, "carve.%s.mk" % prog)
        if not os.path.exists(mk) or open(mk).read() != render_mk(prog, rec):
            errs.append("%s: config/carve.%s.mk != the record" % (prog, prog))
    allprogs = segment.read_programs(segment.BOUNDARIES)
    for prog in sorted(p for p in allprogs if os.path.exists(cfg(root, p + ".yaml"))):
        with open(cfg(root, prog + ".yaml")) as f:
            lines = f.read().split("\n")
        m = segment.marked(lines)
        want = segment.block(prog, allprogs)
        if m is None or lines[m[0]:m[1] + 1] != want:
            errs.append("%s: config/%s.yaml block != segment.py regeneration" % (prog, prog))
    for e in [] if quiet else errs:
        print("CARVE CHECK FAIL " + e)
    if errs:
        return 1
    say("CARVE CHECK OK %d carves" % n)
    return 0


# ---- self-test -----------------------------------------------------------------------------------------------------

EXE = segment.EXE["name"]
PLANTS = ["jtbl 0x80011E00 0x80011E10 - scan planted",
          "jtbl 0x80011E40 0x80011E50 0x800328b0 scan label-inside-scan-table",
          "jtbl 0x80012090 0x800120B0 0x800328b0 both planted-straddle",
          "jtbl 0x80011380 0x80011390 0x800328b0 both planted-overlap"]


def scratch():
    """Fresh copy of the exe's carve inputs under .run/carve-selftest/ (never the real config/src)."""
    shutil.rmtree(SCRATCH, ignore_errors=True)
    os.makedirs(cfg(SCRATCH))
    for p in ["boundaries.txt", "c_units.txt", EXE + ".yaml", "carve.%s.txt" % EXE, "carve.%s.mk" % EXE]:
        if os.path.exists(cfg(ROOT, p)):
            shutil.copy(cfg(ROOT, p), cfg(SCRATCH, p))
    shutil.copytree(os.path.join(ROOT, "src", EXE), os.path.join(SCRATCH, "src", EXE))
    shutil.copytree(os.path.join(ROOT, "src", "shared"), os.path.join(SCRATCH, "src", "shared"))
    use_root(SCRATCH)


def expect(code, fn, *a):
    try:
        fn(*a)
    except Refuse as e:
        ok = (" %s " % code) in str(e) + " "
        print("control %-15s %s" % (code, "tripped" if ok else "WRONG: " + str(e)))
        return ok
    print("control %-15s NOT refused" % code)
    return False


def self_test():
    ok = True
    scratch()
    ok &= check(SCRATCH, quiet=True) == 0
    print("control check-baseline %s" % ("passed" if ok else "FAILED"))
    y = cfg(SCRATCH, EXE + ".yaml")
    with open(y) as f:
        orig = f.read()
    with open(y, "w") as f:
        f.write(orig.replace(", rodata, 10000]", ", rodata, 10004]", 1))
    t = check(SCRATCH, quiet=True) != 0
    print("control check-yaml-edit %s" % ("tripped" if t else "NOT refused"))
    ok &= t
    with open(y, "w") as f:
        f.write(orig)
    bp = segment.BOUNDARIES
    with open(bp) as f:
        b = f.read()
    hdr = b.index("# program %s " % EXE)
    eol = b.index("\n", hdr) + 1
    with open(bp, "w") as f:
        f.write(b[:eol] + "\n".join(PLANTS) + "\n" + b[eol:])
    if not any(r[0] == "jtbl" and int(r[1], 16) == 0x80011378 for r in read_record(SCRATCH, EXE)):
        carve_jtbl(SCRATCH, EXE, 0x80011378)  # the positive control (when the real record lacks it)
    ok &= expect("not-a-row", carve_jtbl, SCRATCH, EXE, 0x80011379)
    ok &= expect("no-dispatcher", carve_jtbl, SCRATCH, EXE, 0x80011E00)
    ok &= expect("no-dispatcher", carve_jtbl, SCRATCH, EXE, 0x80011E40)
    ok &= expect("straddles", carve_jtbl, SCRATCH, EXE, 0x80012090)
    ok &= expect("overlaps-carve", carve_jtbl, SCRATCH, EXE, 0x80011380)
    ok &= expect("non-contiguous", carve_jtbl, SCRATCH, EXE, 0x80011398)
    fns = corpus(EXE)
    tu = fns[0x800429C4][1]
    ok &= expect("not-a-start", carve_opt, SCRATCH, EXE, tu, 0x800429C8, "")
    start = dict((n, v) for v, n in text_tus(EXE))[tu]
    ok &= expect("tu-start", carve_opt, SCRATCH, EXE, tu, start, "")
    carve_opt(SCRATCH, EXE, tu, 0x800429C4, "-O0 -G0")  # positive control: a C-definition chunk moves
    src = os.path.join(SCRATCH, "src", EXE)
    with open(os.path.join(src, "429C4.c")) as f:
        new = f.read()
    with open(os.path.join(src, tu + ".c")) as f:
        head = f.read()
    t = (new.startswith('#include "common.h"\n\nvoid func_800429C4(void) {') and "func_800429C4" not in head
         and "nonmatchings/%s\"" % tu not in new and "CFLAGS_429C4 := -O0 -G0" in open(cfg(SCRATCH, "carve.%s.mk" % EXE)).read()
         and "%s 429C4" % EXE in open(cfg(SCRATCH, "c_units.txt")).read())
    print("control opt-split     %s" % ("moved" if t else "WRONG"))
    ok &= t
    use_root(ROOT)
    if not ok:
        print("CARVE CONTROL FAILED")
        return 1
    print("CARVE CONTROL OK")
    return 0


def main(argv):
    try:
        if argv[:1] == ["--self-test"]:
            return self_test()
        if argv[:1] == ["--check"]:
            return check(ROOT)
        use_root(ROOT)
        if len(argv) == 3 and argv[0] == "jtbl":
            carve_jtbl(ROOT, argv[1], int(argv[2], 16))
            return 0
        if len(argv) in (4, 6) and argv[0] == "opt" and (len(argv) == 4 or argv[4] == "--cflags"):
            carve_opt(ROOT, argv[1], argv[2], int(argv[3], 16), argv[5] if len(argv) == 6 else "")
            return 0
    except Refuse as e:
        print(e)
        return 1
    print(__doc__.strip())
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
