#!/usr/bin/env python3
"""segment.py -- splat subsegment list of one program from config/boundaries.txt (stdlib only).

    segment.py <bin> [--print]      bin = SLUS_013.95 | rock_NN

Applies config/segmentation.md "Rules per row kind": only non-weak lib rows make forced edges; weak rows
(LIBSND.LIB/VM_VIB.OBJ) are dropped first; a span wholly inside an earlier span is dropped; a partial overlap
merges into one `A+B` TU; each gap between edges is one TU named by its vram hex without the 0x80 prefix.
Rewrites only the block between the BEGIN/END markers in config/<bin>.yaml; --print (and every overlay, which
has no yaml yet) writes the block to stdout instead.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BOUNDARIES = os.path.join(ROOT, "config", "boundaries.txt")
BEGIN = "# BEGIN generated by tools/mmx6/segment.py"
END = "# END generated by tools/mmx6/segment.py"
INDENT = "      "
WEAK = {"LIBSND.LIB/VM_VIB.OBJ"}

# Exe layout (config/segmentation.md "Terms"; developer decision T3 review): file off = vram - base + 0x800.
EXE = {"name": "SLUS_013.95", "header": 0x800, "rodata_lo": 0x80010000, "text_lo": 0x800120A0,
       "text_hi_min": 0x8006D5D0}


def read_programs(path):
    """{program: (base, size, [(lo, hi, name), ...])} from the `# program` headers and lib rows."""
    progs, cur = {}, None
    with open(path) as f:
        for line in f:
            w = line.split()
            if line.startswith("# program "):
                cur = w[2]
                progs[cur] = (int(w[4], 16), int(w[6], 16), [])
            elif w and w[0] == "lib" and cur is not None:
                progs[cur][2].append((int(w[1], 16), int(w[2], 16), w[3]))
    return progs


def lib_spans(rows):
    """Kept lib spans after the weak drop, containment drop and partial-overlap merge, sorted by lo."""
    kept = []
    for lo, hi, name in sorted((r for r in rows if r[2] not in WEAK), key=lambda r: (r[0], -r[1], r[2])):
        if kept and lo < kept[-1][1]:
            plo, phi, pname = kept[-1]
            if hi <= phi:
                continue  # wholly inside the earlier span: the container wins
            kept[-1] = (plo, hi, pname + "+" + name)  # partial overlap: one A+B TU
            continue
        kept.append((lo, hi, name))
    return kept


def tu_name(name):
    """LIBSPU.LIB/SPU.OBJ -> LIBSPU_SPU; A+B joined part-wise."""
    return "+".join("_".join(p.split(".")[0] for p in part.split("/")) for part in name.split("+"))


def hexname(vram):
    return "%X" % (vram - 0x80000000)


def text_tus(spans, lo, hi):
    """[(vram, name)] covering [lo, hi): one TU per lib span, one per gap."""
    tus, at = [], lo
    for slo, shi, name in spans:
        if slo > at:
            tus.append((at, hexname(at)))
        tus.append((slo, tu_name(name)))
        at = shi
    if hi > at:
        tus.append((at, hexname(at)))
    seen, out = set(), []
    for vram, name in tus:
        if name in seen:
            name = "%s_%s" % (name, hexname(vram))
        seen.add(name)
        out.append((vram, name))
    return out


def block(prog, progs):
    base, size, rows = progs[prog]
    spans = lib_spans(rows)
    if prog == EXE["name"]:
        off = lambda v: v - base + EXE["header"]
        text_hi = max([EXE["text_hi_min"]] + [s[1] for s in spans])
        end = base + size
        lines = ["[0x%X, rodata, %s]" % (off(EXE["rodata_lo"]), hexname(EXE["rodata_lo"]))]
        lines += ["[0x%X, asm, %s]" % (off(v), n) for v, n in text_tus(spans, EXE["text_lo"], text_hi)]
        lines.append("[0x%X, data, %s]" % (off(text_hi), hexname(text_hi)))
        lines.append("{ start: 0x%X, type: bss, vram: 0x%X, name: %s }" % (off(end), end, hexname(end)))
    else:
        lines = ["[0x%X, asm, %s]" % (v - base, n) for v, n in text_tus(spans, base, base + size)]
    return [INDENT + BEGIN] + [INDENT + "- " + l for l in lines] + [INDENT + END]


def main(argv):
    if not argv or argv[0].startswith("-"):
        print(__doc__.strip())
        return 2
    prog, to_stdout = argv[0], "--print" in argv[1:]
    progs = read_programs(BOUNDARIES)
    if prog not in progs:
        print("segment.py: no program %s in %s" % (prog, BOUNDARIES), file=sys.stderr)
        return 2
    out = block(prog, progs)
    yaml_path = os.path.join(ROOT, "config", prog + ".yaml")
    if to_stdout or not os.path.exists(yaml_path):
        print("\n".join(out))
        return 0
    with open(yaml_path) as f:
        lines = f.read().split("\n")
    starts = [i for i, l in enumerate(lines) if l.strip() == BEGIN]
    ends = [i for i, l in enumerate(lines) if l.strip() == END]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        print("segment.py: %s needs exactly one BEGIN/END marker pair" % yaml_path, file=sys.stderr)
        return 1
    lines[starts[0]:ends[0] + 1] = out
    with open(yaml_path, "w") as f:
        f.write("\n".join(lines))
    print("%s: %d text TUs" % (yaml_path, sum(" asm, " in l for l in out)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
