#!/usr/bin/env python3
"""segment.py -- splat subsegment list of one program from config/boundaries.txt (stdlib only).

    segment.py <bin> [--print | --init]      bin = SLUS_013.95 | rock_NN

Applies config/segmentation.md "Rules per row kind": only non-weak lib rows make forced edges; weak rows
(LIBSND.LIB/VM_VIB.OBJ) are dropped first; a span wholly inside an earlier span is dropped; a partial overlap
merges into one `A+B` TU; each gap between edges is one TU named by its vram hex without the 0x80 prefix.
Rewrites only the block between the BEGIN/END markers in config/<bin>.yaml; --print (or a missing yaml without
--init) writes the block to stdout instead. --init, for a `code` member of config/loadmap.txt with no yaml, first
writes config/rock_NN.yaml (vram = loadmap base, sha1/size from manifest/retail.jsonl), config/symbols.rock_NN.txt
and config/check.rock_NN.sha. An overlay's asm TUs end at size & ~3; a 1-3 byte remainder is a `bin` subsegment.
All overlays: `for k in $(awk '$3=="code" && $1~/^[0-9]+$/{printf "rock_%02d\n",$1}' config/loadmap.txt); do
segment.py $k --init; done`.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BOUNDARIES = os.path.join(ROOT, "config", "boundaries.txt")
LOADMAP = os.path.join(ROOT, "config", "loadmap.txt")
MANIFEST = os.path.join(ROOT, "manifest", "retail.jsonl")
GP = 0x8008EAA4  # exe gp (docs/memory-map.md ## gp, T2); overlays share it
BEGIN = "# BEGIN generated by tools/mmx6/segment.py"
END = "# END generated by tools/mmx6/segment.py"
INDENT = "      "
WEAK = {"LIBSND.LIB/VM_VIB.OBJ"}

# Exe layout (config/segmentation.md "Terms"; developer decision T3 review): file off = vram - base + 0x800.
EXE = {"name": "SLUS_013.95", "header": 0x800, "rodata_lo": 0x80010000, "text_lo": 0x800120A0,
       "text_hi_min": 0x8006D5D0}


def read_programs(path):
    """{program: (base, size, [(lo, hi, name), ...])} from the `# program` headers and lib rows."""
    progs, cur = {}, None
    with open(path) as f:
        for line in f:
            w = line.split()
            if line.startswith("# program "):
                cur = w[2]
                progs[cur] = (int(w[4], 16), int(w[6], 16), [])
            elif w and w[0] == "lib" and cur is not None:
                progs[cur][2].append((int(w[1], 16), int(w[2], 16), w[3]))
    return progs


def lib_spans(rows):
    """Kept lib spans after the weak drop, containment drop and partial-overlap merge, sorted by lo."""
    kept = []
    for lo, hi, name in sorted((r for r in rows if r[2] not in WEAK), key=lambda r: (r[0], -r[1], r[2])):
        if kept and lo < kept[-1][1]:
            plo, phi, pname = kept[-1]
            if hi <= phi:
                continue  # wholly inside the earlier span: the container wins
            kept[-1] = (plo, hi, pname + "+" + name)  # partial overlap: one A+B TU
            continue
        kept.append((lo, hi, name))
    return kept


def tu_name(name):
    """LIBSPU.LIB/SPU.OBJ -> LIBSPU_SPU; A+B joined part-wise."""
    return "+".join("_".join(p.split(".")[0] for p in part.split("/")) for part in name.split("+"))


def hexname(vram):
    return "%X" % (vram - 0x80000000)


def text_tus(spans, lo, hi):
    """[(vram, name)] covering [lo, hi): one TU per lib span, one per gap."""
    tus, at = [], lo
    for slo, shi, name in spans:
        if slo > at:
            tus.append((at, hexname(at)))
        tus.append((slo, tu_name(name)))
        at = shi
    if hi > at:
        tus.append((at, hexname(at)))
    seen, out = set(), []
    for vram, name in tus:
        if name in seen:
            name = "%s_%s" % (name, hexname(vram))
        seen.add(name)
        out.append((vram, name))
    return out


def block(prog, progs):
    base, size, rows = progs[prog]
    spans = lib_spans(rows)
    if prog == EXE["name"]:
        off = lambda v: v - base + EXE["header"]
        text_hi = max([EXE["text_hi_min"]] + [s[1] for s in spans])
        end = base + size
        lines = ["[0x%X, rodata, %s]" % (off(EXE["rodata_lo"]), hexname(EXE["rodata_lo"]))]
        lines += ["[0x%X, asm, %s]" % (off(v), n) for v, n in text_tus(spans, EXE["text_lo"], text_hi)]
        lines.append("[0x%X, data, %s]" % (off(text_hi), hexname(text_hi)))
        lines.append("{ start: 0x%X, type: bss, vram: 0x%X, name: %s }" % (off(end), end, hexname(end)))
    else:
        top = size & ~3  # asm needs whole words; the 1-3 byte remainder is raw bytes
        lines = ["[0x%X, asm, %s]" % (v - base, n) for v, n in text_tus(spans, base, base + top)]
        if top != size:
            lines.append("[0x%X, bin, %s]" % (top, hexname(base + top)))
    return [INDENT + BEGIN] + [INDENT + "- " + l for l in lines] + [INDENT + END]


OVERLAY_YAML = """\
# splat 0.50.0 config for overlay {prog} (rock/{k:02d}.bin, phase 1.3 T5, coarse all-asm baseline).
# Raw image, no header: file off = vram - 0x{base:08X} (config/loadmap.txt member {k} base); size 0x{size:X}.
# Generated by tools/mmx6/segment.py --init; subsegments between the BEGIN/END markers are regenerated by
# tools/mmx6/segment.py (config/segmentation.md). gp = exe gp (docs/memory-map.md "Overlay builds").
name: {prog}
sha1: {sha1}
options:
  platform: psx
  basename: {prog}
  base_path: ..
  target_path: extracted/retail/rock/{k:02d}.bin
  asm_path: asm/{prog}
  asset_path: asm/{prog}/assets
  src_path: src/{prog}
  build_path: build
  ld_script_path: build/{prog}.ld
  undefined_funcs_auto_path: build/undefined_funcs_auto.{prog}.txt
  undefined_syms_auto_path: build/undefined_syms_auto.{prog}.txt
  symbol_addrs_path:
    - config/symbols.{prog}.txt
  compiler: GCC
  gp_value: 0x{gp:08X}
  ld_bss_is_noload: true
  use_legacy_include_asm: false
  asm_jtbl_label_macro: jlabel
  section_order: [".rodata", ".text", ".data", ".bss"]
  subalign: 4 # as config/SLUS_013.95.yaml (T4.c1)
  ld_align_section_vram_end: false # as config/SLUS_013.95.yaml (T4.c1)
segments:
  - name: {prog}
    type: code
    start: 0x0
    vram: 0x{base:08X}
    subsegments:
      {begin}
      {end}
  - [0x{size:X}]
"""

OVERLAY_SYMBOLS = """\
// splat symbol_addrs for {prog}. splat parses `key:value` tokens in a trailing comment as attributes, so each
// symbol's `basis: <src>` sits on the comment line above it (G62). No symbols yet.
"""


def init_overlay(prog):
    """Write config/<prog>.yaml, symbols and check files for a loadmap `code` member; rc."""
    k = int(prog[len("rock_"):])
    row = None
    with open(LOADMAP) as f:
        for line in f:
            w = line.split()
            if len(w) >= 3 and w[0] == str(k):
                row = w
    if row is None or row[2] != "code" or row[1] == "-" or "," in row[1]:
        print("segment.py: member %d is not a single-base code row of %s" % (k, LOADMAP), file=sys.stderr)
        return 1
    rock = None
    with open(MANIFEST) as f:
        for line in f:
            r = json.loads(line)
            if r.get("kind") == "rock" and r.get("index") == k:
                rock = r
    if rock is None:
        print("segment.py: no rock row %d in %s" % (k, MANIFEST), file=sys.stderr)
        return 1
    cfg = os.path.join(ROOT, "config")
    with open(os.path.join(cfg, prog + ".yaml"), "w") as f:
        f.write(OVERLAY_YAML.format(prog=prog, k=k, base=int(row[1], 16), size=rock["size"], sha1=rock["sha1"],
                                    gp=GP, begin=BEGIN, end=END))
    with open(os.path.join(cfg, "symbols.%s.txt" % prog), "w") as f:
        f.write(OVERLAY_SYMBOLS.format(prog=prog))
    with open(os.path.join(cfg, "check.%s.sha" % prog), "w") as f:
        f.write("%s  build/rock/%02d.bin\n" % (rock["sha1"], k))
    return 0


def main(argv):
    if not argv or argv[0].startswith("-"):
        print(__doc__.strip())
        return 2
    prog, to_stdout = argv[0], "--print" in argv[1:]
    progs = read_programs(BOUNDARIES)
    if prog not in progs:
        print("segment.py: no program %s in %s" % (prog, BOUNDARIES), file=sys.stderr)
        return 2
    out = block(prog, progs)
    yaml_path = os.path.join(ROOT, "config", prog + ".yaml")
    if "--init" in argv[1:] and prog.startswith("rock_") and not os.path.exists(yaml_path):
        rc = init_overlay(prog)
        if rc:
            return rc
    if to_stdout or not os.path.exists(yaml_path):
        print("\n".join(out))
        return 0
    with open(yaml_path) as f:
        lines = f.read().split("\n")
    starts = [i for i, l in enumerate(lines) if l.strip() == BEGIN]
    ends = [i for i, l in enumerate(lines) if l.strip() == END]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        print("segment.py: %s needs exactly one BEGIN/END marker pair" % yaml_path, file=sys.stderr)
        return 1
    lines[starts[0]:ends[0] + 1] = out
    with open(yaml_path, "w") as f:
        f.write("\n".join(lines))
    print("%s: %d text TUs" % (yaml_path, sum(" asm, " in l for l in out)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
