# config/carve.SLUS_013.95.mk -- generated by tools/mmx6/carve.py from config/carve.SLUS_013.95.txt; included by the Makefile.
build/src/SLUS_013.95/32208.c.o: CFLAGS_32208 := -O2 -G0 -msoft-float -funsigned-char -quiet
