/* Adapted from sozud/mmx4 @29b62af include/common.h, include/func_tables.h, include/psy-q-4.0/LIBCD.H, include/psy-q-4.0/LIBGPU.H, include/psy-q-4.0/SYS/TYPES.H, include/scratchpad.h, src/main/3D88.c, AGPL-3.0; proven shared with X6 by the exact signature each including draft names (see THIRD_PARTY.md). */
/* Generated by tools/mmx6/x4port.py --wave (never hand-edited): the X4_ types and mmx4 macros the W-x4 drafts use. */
#ifndef MMX6_X4_H
#define MMX6_X4_H

#include "common.h"

#ifndef ANIMATED_OBJECT
#define ANIMATED_OBJECT(object) ((struct X4_AnimatedObj*)(object))
#endif
#ifndef BASE_OBJECT
#define BASE_OBJECT(object) ((struct X4_BaseObj*)(object))
#endif
#ifndef BLINK_CLOCK
#define BLINK_CLOCK(timer) (timer)
#endif
#ifndef COUNT
#define COUNT(x) (sizeof(x) / sizeof(x[0]))
#endif
#ifndef CdlPause
#define CdlPause 0x09
#endif
#ifndef FIXED
#define FIXED(x) ((s32)((x)*0x10000))
#endif
#ifndef FLICKER_ENABLED
#define FLICKER_ENABLED 1
#endif
#ifndef MIN
#define MIN(a,b) ((a) < (b) ? (a) : (b))
#endif
#ifndef MOVING_OBJECT
#define MOVING_OBJECT(object) ((struct X4_MovingObj*)(object))
#endif
#ifndef NULL
#define NULL ((void*)0)
#endif
#ifndef OBJECT_HEADER
#define OBJECT_HEADER(object) ((struct X4_ObjectHeader*)(object))
#endif
#ifndef SP
#define SP(offset) (0x1F800000 + (offset))
#endif
#ifndef SP_BG_TILEMAP
#define SP_BG_TILEMAP (*(u8**)SP(0x004))
#endif
#ifndef SP_BG_TILE_ATTRS
#define SP_BG_TILE_ATTRS (*(u32**)SP(0x00C))
#endif
#ifndef SP_BG_TILE_PIXELS
#define SP_BG_TILE_PIXELS (*(u16**)SP(0x008))
#endif
#ifndef SP_CUR_MAIN_OBJ
#define SP_CUR_MAIN_OBJ (*(struct X4_MainObj**)SP(0x04C))
#endif
#ifndef SP_DRAW_BUFFER
#define SP_DRAW_BUFFER (*(s32*)SP(0x000))
#endif
#ifndef SP_SPRITE_FRAMES
#define SP_SPRITE_FRAMES (*(s32**)SP(0x01C))
#endif
#ifndef VISUAL_OBJECT
#define VISUAL_OBJECT(object) ((struct X4_VisualObj*)(object))
#endif
#ifndef X4_D_u_char
#define X4_D_u_char
typedef unsigned char X4_u_char;
#endif
#ifndef X4_D_CdlLOC
#define X4_D_CdlLOC
typedef struct {
 X4_u_char minute;
 X4_u_char second;
 X4_u_char sector;
 X4_u_char track;
} X4_CdlLOC;
#endif
#ifndef X4_D_CdSectorBuffer
#define X4_D_CdSectorBuffer
union X4_CdSectorBuffer {
    u8 sectors[16][0x800];
    u32 words[0x2000];
};
#endif
#ifndef X4_D_CdCompletionSlot
#define X4_D_CdCompletionSlot
struct X4_CdCompletionSlot {
    u8 pending, callback;
    u16 pad2;
    u32 callback_arg;
    u16 transfer_pending, padA;
};
#endif
#ifndef X4_D_CdlCB
#define X4_D_CdlCB
typedef void (*X4_CdlCB)(X4_u_char,X4_u_char *);
#endif
#ifndef X4_D_f32
#define X4_D_f32
typedef union {
    s32 val;
    struct {
        s16 lo;
        s16 hi;
    } i;
    struct {
        u16 lo;
        u16 hi;
    } u;
    u8 bytes[4];
} X4_f32;
#endif
#ifndef X4_D_AnimationStep
#define X4_D_AnimationStep
union X4_AnimationStep {
    u32 packed;
    struct {
        s8 duration;
        s8 event;
        s8 relative_step;
        u8 frame_index;
    } fields;
};
#endif
#ifndef X4_D_AnimatedObj
#define X4_D_AnimatedObj
struct X4_AnimatedObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17; X4_f32 unk18; X4_f32 unk1C; X4_f32 x_vel; X4_f32 y_vel; s32 unk28; s32 unk2C; u32** animation_table; u32* animation_cursor; void* unk38; void* unk3C; u16 unk40; u16 unk42; union X4_AnimationStep animation_step; u8 previous_animation_index;
};
#endif
#ifndef X4_D_u_long
#define X4_D_u_long
typedef unsigned long X4_u_long;
#endif
#ifndef X4_D_RECT
#define X4_D_RECT
typedef struct {
 short x, y;
 short w, h;
} X4_RECT;
#endif
#ifndef X4_D_RectPtrPair
#define X4_D_RectPtrPair
struct X4_RectPtrPair {
    X4_RECT rect;
    X4_u_long* ptr;
};
#endif
#ifndef X4_D_CdlATV
#define X4_D_CdlATV
typedef struct {
 X4_u_char val0;
 X4_u_char val1;
 X4_u_char val2;
 X4_u_char val3;
} X4_CdlATV;
#endif
#ifndef X4_D_MemcardPath
#define X4_D_MemcardPath
struct X4_MemcardPath {
    char path[6];
};
#endif
#ifndef X4_D_GameInfo
#define X4_D_GameInfo
struct X4_GameInfo {
    s8 unk0;
    s8 mode;
    s8 unk2;
    s8 unk3;
    s16 unk4;
    s16 unk6;
    s16 unk8;
    s16 unkA;
    s8 unkC;
    s8 unkD;
    s8 unkE;
    s8 unkF;
};
#endif
#ifndef X4_D_FixedPointPosition
#define X4_D_FixedPointPosition
struct X4_FixedPointPosition {
    s32 x;
    s32 y;
};
#endif
#ifndef X4_D_PlayerUnk8A
#define X4_D_PlayerUnk8A
union X4_PlayerUnk8A {
    u16 packed;
    struct {
        u8 low;
        s8 high;
    } bytes;
};
#endif
#ifndef X4_D_PlayerUnkDC
#define X4_D_PlayerUnkDC
union X4_PlayerUnkDC {
    s16 value;
    u16 unsigned_value;
};
#endif
#ifndef X4_D_PlayerChargeState
#define X4_D_PlayerChargeState
typedef s8 X4_PlayerChargeState;
#endif
#ifndef X4_D_ObjectHeader
#define X4_D_ObjectHeader
struct X4_ObjectHeader {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref;
};
#endif
#ifndef X4_D_BaseObj
#define X4_D_BaseObj
struct X4_BaseObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17;
};
#endif
#ifndef X4_D_Main0Ext
#define X4_D_Main0Ext
struct X4_Main0Ext {
    u8 background_relative;
    u8 index;
    u8 flags[3];
    u8 exit_mode;
    u8 damage_flash_timer;
};
#endif
#ifndef X4_D_Main3Ext
#define X4_D_Main3Ext
struct X4_Main3Ext {
    u32 alerted;
    s32 roll_timer;
    u32 player_ahead;
    u32 turn_timer;
    u32 saved_step;
};
#endif
#ifndef X4_D_Main5Ext
#define X4_D_Main5Ext
struct X4_Main5Ext {
    u8 unk80;
    u8 pad81[6];
    u8 lifetime;
    u8 spawn_timer;
    u8 pad89[2];
    u8 unk8B;
    u16 saved_unk5;
    u16 part_index;
    u16 target_x;
    u16 target_y;
    struct X4_MainObj* owner;
};
#endif
#ifndef X4_D_Main6Ext
#define X4_D_Main6Ext
struct X4_Main6Ext {
    u32 armor_broken;
    u32 ground_probe_distance;
    u32 armor_health;
    u32 core_health;
    u32 hitbox_toggle;
    u32 saved_step;
};
#endif
#ifndef X4_D_Main58Ext
#define X4_D_Main58Ext
struct X4_Main58Ext {
    u32 saved_unk5, unk84, unk88;
};
#endif
#ifndef X4_D_Main10Ext
#define X4_D_Main10Ext
struct X4_Main10Ext {
    u32 timer;
    s32 turn_delay;
    s32 struggle;
    u32 hold_state;
    u32 can_grab;
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main14Ext
#define X4_D_Main14Ext
struct X4_Main14Ext {
    u32 unk80;
    u32 unk84;
    s32 visual_variant;
    u32 unk8C;
    u32 saved_unk5;
    u32 unk94;
};
#endif
#ifndef X4_D_Main16Ext
#define X4_D_Main16Ext
struct X4_Main16Ext {
    u32 unk80;
    s32 unk84;
    s32 unk88;
    u32 unk8C;
    u32 unk90;
    u32 shot_09_active;
    u32 unk98;
};
#endif
#ifndef X4_D_Main17Ext
#define X4_D_Main17Ext
struct X4_Main17Ext {
    u32 unk80;
    u32 unk84;
    u32 unk88;
    u32 unk8C;
    u32 unk90;
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main37Unk80
#define X4_D_Main37Unk80
union X4_Main37Unk80 {
    u32 word;
    u8 saved_direction;
};
#endif
#ifndef X4_D_Main37Ext
#define X4_D_Main37Ext
struct X4_Main37Ext {
    union X4_Main37Unk80 unk80;
    X4_f32 unk84;
    X4_f32 unk88;
    X4_f32 unk8C;
    u8 pad90[4];
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main32Ext
#define X4_D_Main32Ext
struct X4_Main32Ext {
    u32 unk80;
    u32 unk84;
    s32 unk88;
    u32 unk8C;
    u32 unk90;
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main33Ext
#define X4_D_Main33Ext
struct X4_Main33Ext {
    u8 unk80;
    u8 variant;
    s16 target_x;
    u8 unk84;
    u8 intro_active;
    u8 intro_laps;
    u8 unk87;
    s16 unk88;
    u8 pad8A[4];
    u16 unk8E;
    u8 flash_timer;
    u8 unk91;
    u8 pad92[2];
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main34Ext
#define X4_D_Main34Ext
struct X4_Main34Ext {
    s8 unk80;
    u8 pad81;
    u8 unk82;
};
#endif
#ifndef X4_D_Main38Ext
#define X4_D_Main38Ext
struct X4_Main38Ext {
    u32 saved_unk5;
    s32 unk84;
    u32 unk88;
    u32 unk8C;
    u32 unk90;
    u32 unk94;
};
#endif
#ifndef X4_D_Main39Ext
#define X4_D_Main39Ext
struct X4_Main39Ext {
    union {
        struct {
            u16 unk80;
            s16 unk82;
        } h;
        u32 w;
    } unk80;
    union {
        struct {
            s16 unk84;
            u16 unk86;
        } h;
        u32 w;
    } unk84;
    u8 unk88;
    u8 pad89[3];
    s32 unk8C;
    s32 unk90;
    u8 unk94;
};
#endif
#ifndef X4_D_Main40Ext
#define X4_D_Main40Ext
struct X4_Main40Ext {
    u8 unk80;
    u8 unk81;
    u16 timer;
    u16 trigger_time;
};
#endif
#ifndef X4_D_MainSavedState94Ext
#define X4_D_MainSavedState94Ext
struct X4_MainSavedState94Ext {
    u32 unk80;
    u32 unk84;
    u32 unk88;
    u32 unk8C;
    u32 unk90;
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main51Ext
#define X4_D_Main51Ext
struct X4_Main51Ext {
    u32 unk80;
    u32 unk84;
    u8 pad88[8];
    u32 unk90;
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main7Ext
#define X4_D_Main7Ext
struct X4_Main7Ext {
    u32 unk80;
    u32 unk84;
    s32 saved_x_velocity;
    s32 saved_y_velocity;
    u32 unk90;
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main52Ext
#define X4_D_Main52Ext
struct X4_Main52Ext {
    u8 unk80;
    u8 pad81[3];
    u8 unk84;
    u8 pad85[3];
    u8 unk88;
    u8 pad89[3];
    u8 unk8C;
    u8 pad8D[7];
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main13Ext
#define X4_D_Main13Ext
struct X4_Main13Ext {
    u32 unk80;
    u32 unk84;
    u32 unk88;
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main11Ext
#define X4_D_Main11Ext
struct X4_Main11Ext {
    u8 unk80;
    u8 pad81[6];
    u8 saved_unk5;
};
#endif
#ifndef X4_D_Main12Ext
#define X4_D_Main12Ext
struct X4_Main12Ext {
    u8 unk80;
    u8 unk81;
    u8 saved_unk5;
    u8 pad83[3];
    u16 unk86;
    u16 unk88;
    u16 unk8A;
    u16 unk8C;
};
#endif
#ifndef X4_D_Main22Ext
#define X4_D_Main22Ext
struct X4_Main22Ext {
    u32 saved_unk5;
    u32 unk84;
    u8 pad88[4];
    u32 unk8C;
    u32 unk90;
    u32 parts_mask;
};
#endif
#ifndef X4_D_Main26Ext
#define X4_D_Main26Ext
struct X4_Main26Ext {
    s8 last_health;
    s8 stage;
};
#endif
#ifndef X4_D_Main23Ext
#define X4_D_Main23Ext
struct X4_Main23Ext {
    u8 unk80;
    u8 unk81;
    u8 unk82;
};
#endif
#ifndef X4_D_Main24Ext
#define X4_D_Main24Ext
struct X4_Main24Ext {
    u32 unk80;
    u8 pad84[0x10];
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main47Ext
#define X4_D_Main47Ext
struct X4_Main47Ext {
    struct X4_BaseObj* unk80;
    u32 unk84;
    u32 unk88;
    u32 unk8C;
    u32 unk90;
    u32 unk94;
};
#endif
#ifndef X4_D_Main76Ext
#define X4_D_Main76Ext
struct X4_Main76Ext {
    s32 saved_x_velocity;
};
#endif
#ifndef X4_D_Main25Ext
#define X4_D_Main25Ext
struct X4_Main25Ext {
    u32 unk80;
    u32 unk84;
    u32 unk88;
    u8 pad8C[8];
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main35Ext
#define X4_D_Main35Ext
struct X4_Main35Ext {
    u32 unk80;
    u32 sound_timer;
    u8 pad88[0xC];
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main45LayerSignals
#define X4_D_Main45LayerSignals
struct X4_Main45LayerSignals {
    u8 unk16;
    u8 collision_state;
    u8 projectile_state[3];
};
#endif
#ifndef X4_D_Main45Ext
#define X4_D_Main45Ext
struct X4_Main45Ext {
    u8 attack_flags;
    u8 unk81;
    u8 unk82;
    u8 unk83;
    s16 unk84;
    u8 unk86;
    u8 unk87;
    u8 projectile_command;
    u8 unk89;
    s16 unk8A;
    u8* layer_bg_offset;
    u8* layer_parameter;
    struct X4_Main45LayerSignals* layer_signals;
};
#endif
#ifndef X4_D_Main48Ext
#define X4_D_Main48Ext
struct X4_Main48Ext {
    s8 unk80;
    u8 unk81;
    s8 unk82;
    s8 unk83;
    u8 saved_unk5;
    u8 collision_result;
    u8 unk86;
    u8 unk87;
    u8 unk88;
};
#endif
#ifndef X4_D_Main73EffectData
#define X4_D_Main73EffectData
union X4_Main73EffectData {
    struct {
        u8 state;
        u8 object_id;
        u8 unk8E;
        u8 pad8F;
    } bytes;
    struct {
        u16 x;
        u16 y;
    } position;
};
#endif
#ifndef X4_D_Main73Ext
#define X4_D_Main73Ext
struct X4_Main73Ext {
    union {
        struct X4_EffectObj* effect;
        s8* script;
    } unk80;
    u8* cycle_script;
    u8 cycle_step;
    u8 shot_count;
    u8 pad8A;
    u8 blink_delay;
    union X4_Main73EffectData effect;
};
#endif
#ifndef X4_D_Main73PartsExt
#define X4_D_Main73PartsExt
struct X4_Main73PartsExt {
    struct X4_MainObj* parts[3];
    u8 effect_state;
    u8 object_id;
    u8 unk8E;
};
#endif
#ifndef X4_D_Main18RuntimeFields
#define X4_D_Main18RuntimeFields
struct X4_Main18RuntimeFields {
    u8 unk80;
    u8 unk81;
    u8 unk82;
    u8 unk83;
    u8 unk84;
    s8 unk85;
    u8 unk86;
    u8 unk87;
};
#endif
#ifndef X4_D_Main18StateData
#define X4_D_Main18StateData
union X4_Main18StateData {
    struct X4_Main18RuntimeFields runtime;
    struct X4_FixedPointPosition saved_position;
};
#endif
#ifndef X4_D_Main18Ext
#define X4_D_Main18Ext
struct X4_Main18Ext {
    union X4_Main18StateData state;
    u8 unk88;
    u8 shed_timer;
    u16 ice_pieces;
    u32 unk8C;
    u32 unk90;
    u8 pad94[3];
    u8 saved_unk5;
};
#endif
#ifndef X4_D_Main19Ext
#define X4_D_Main19Ext
struct X4_Main19Ext {
    u8 unk80;
    u8 animation_index;
    u8 unk82;
    u8 unk83;
    u16 unk84;
    u16 unk86;
    u16 unk88;
    u16 unk8A;
    u8 unk8C;
};
#endif
#ifndef X4_D_Main21Ext
#define X4_D_Main21Ext
struct X4_Main21Ext {
    s16 timer_80;
    s16 timer_82;
    u8 saved_unk5;
};
#endif
#ifndef X4_D_Main49Ext
#define X4_D_Main49Ext
struct X4_Main49Ext {
    u8 unk80;
    u8 index;
    u8 unk82;
    u8 unk83;
    u8 pad84;
    u8 unk85;
    u8 unk86;
};
#endif
#ifndef X4_D_Main50Ext
#define X4_D_Main50Ext
struct X4_Main50Ext {
    u8 pad80[2];
    u16 timer;
    u8 unk84;
};
#endif
#ifndef X4_D_Main54Ext
#define X4_D_Main54Ext
struct X4_Main54Ext {
    u8 flash_timer;
    u8 powered_up;
    u8 was_hit;
    u8 pad83;
    u8 grab;
    u8 active;
    u8 claw_hitbox;
    u8 afterimage_timer;
    u8 crash_timer;
    u8 pattern_set;
    u8 power_hits;
    u8 pad8B;
    struct X4_EffectObj* effect;
    u8* pattern;
    u8 unk94;
    u8 fight_started;
    u8 high_jump;
};
#endif
#ifndef X4_D_Main55Ext
#define X4_D_Main55Ext
struct X4_Main55Ext {
    u8 pad80[5];
    u8 unk85;
    u8 unk86;
    u8 unk87;
    u8 unk88;
};
#endif
#ifndef X4_D_Main36Ext
#define X4_D_Main36Ext
struct X4_Main36Ext {
    u8 pad80[4];
    struct X4_MiscObj* unk84;
    u8 saved_unk5;
    u8 unk89;
    u16 unk8A;
    u8 unk8C;
    u8 unk8D;
};
#endif
#ifndef X4_D_Main43Ext
#define X4_D_Main43Ext
struct X4_Main43Ext {
    struct X4_ShotObj* shot;
    struct X4_EffectObj* effect;
    u16 big_web_done;
    u16 flash_timer;
    u16 animation_index;
    u16 animation_length;
    u16 attack_cooldown;
    u8 attack_count;
    u8 move_direction;
    u8 unk94;
    s8 hurt_collision;
    s8 animation_id;
    s8 animation_set;
};
#endif
#ifndef X4_D_Main46Ext
#define X4_D_Main46Ext
struct X4_Main46Ext {
    struct X4_Main45Ext* owner;
    u8 pad84[0x95 - 0x84];
    u8 unk95;
};
#endif
#ifndef X4_D_Main56Unk89
#define X4_D_Main56Unk89
union X4_Main56Unk89 {
    u8 value;
    s8 signed_value;
};
#endif
#ifndef X4_D_Main56Unk80
#define X4_D_Main56Unk80
union X4_Main56Unk80 {
    struct X4_EffectObj* effect;
    struct X4_VisualObj* visual;
};
#endif
#ifndef X4_D_Main56Ext
#define X4_D_Main56Ext
struct X4_Main56Ext {
    union X4_Main56Unk80 object;
    u8* pattern;
    u8 vortex_result;
    union X4_Main56Unk89 unk89;
    u8 flash_timer;
    u8 flags;
};
#endif
#ifndef X4_D_Main57Ext
#define X4_D_Main57Ext
struct X4_Main57Ext {
    struct X4_EffectObj* effect;
    struct X4_ShotObj* shot;
    u8* script;
    X4_RECT* rect;
    u8 leap_grounded;
    u8 shard_count;
    u8 tusks_broken;
    u8 flashing;
    u8 flash_timer;
    u8 staggered;
};
#endif
#ifndef X4_D_Main487Ext
#define X4_D_Main487Ext
struct X4_Main487Ext {



    u8 pad80[0xA];

    u8 unk8A;
};
#endif
#ifndef X4_D_Main53Ext
#define X4_D_Main53Ext
struct X4_Main53Ext {
    u8 unk80;
    u8 unk81;
    u8 unk82;
    u8 unk83;
    u8 unk84;
    u8 unk85;
};
#endif
#ifndef X4_D_Main62Ext
#define X4_D_Main62Ext
struct X4_Main62Ext {
    struct X4_VisualObj* unk80;
    u8 pad84[2];
    u8 unk86;
};
#endif
#ifndef X4_D_Main71Ext
#define X4_D_Main71Ext
struct X4_Main71Ext {
    u8 pad80[4];
    s16 unk84;
    u8 unk86;
    u8 unk87;
    u8 unk88;
    u8 pad89;
    u8 unk8A;
    u8 pad8B[2];
    u8 unk8D;
    u8 unk8E;
};
#endif
#ifndef X4_D_Main72Ext
#define X4_D_Main72Ext
struct X4_Main72Ext {
    u8 pad80[4];
    s16 unk84;
    u8 pad86;
    u8 lifetime;
    u8 spawn_timer;
};
#endif
#ifndef X4_D_Main60Ext
#define X4_D_Main60Ext
struct X4_Main60Ext {
    struct X4_EffectObj* effect;
    u8* pattern;
    u16 feather_mask;
    u8 saved_unk5;
    u8 corner;
    u8 pad8C;
    u8 shot_count;
    u8 feathers_holding;
    u8 storm_active;
    u8 storm_timer;
    u8 unk91;
    u8 patrol_delay;
    u8 flash_timer;
    u8 flash_mode;
};
#endif
#ifndef X4_D_Main61Data
#define X4_D_Main61Data
union X4_Main61Data {
    s8* script;
    struct X4_EffectObj* effect;
};
#endif
#ifndef X4_D_Main61Ext
#define X4_D_Main61Ext
struct X4_Main61Ext {
    union X4_Main61Data data;
    u8 flash_timer;
    u8 split;
    u8 blink_timer;
    u8 combo_count;
    u8 stunned;
    u8 split_hits;
    u8 merge;
    u8 active;
    u8 speed_level;
    u8 hit_lock;
    u8 split_done;
    u8 pad8F[0x94 - 0x8F];
    struct X4_MainObj* partner;
};
#endif
#ifndef X4_D_Main65Ext
#define X4_D_Main65Ext
struct X4_Main65Ext {
    struct X4_MainObj* object;
    struct X4_MainObj* smoke;
    s16 jump_start_y;
    u8 flash_timer;
    u8 leap_frames;
    u8 leap_to_right;
    u8 attack;
    u8 attack_repeat;
};
#endif
#ifndef X4_D_Main64Ext
#define X4_D_Main64Ext
struct X4_Main64Ext {
    void* object;
    u16 target_x;
    u16 target_y;
    u8 skip_attack;
    u8 next_step;
    u8 unk8A;
    u8 shot_count;
    s16 arena_x;
    s16 arena_y;
    u8 hit_count;
    u8 force_laser;
    u8 flash_timer;
    u8 saved_health;
};
#endif
#ifndef X4_D_Main74Ext
#define X4_D_Main74Ext
struct X4_Main74Ext {
    struct X4_MainObj* children[3];
    u8 unk8C;
    u8 effect_state;
    u8 unk8E;
    u8 timer;
    u8 animation_index;
    u8 target;
    u8 upper_health;
    u8 lower_health;
    u8 death_kind;
    u8 pad95;
    u8 pattern_index;
    u8 unk97;
};
#endif
#ifndef X4_D_Main75Ext
#define X4_D_Main75Ext
struct X4_Main75Ext {
    union {
        struct X4_EffectObj* effect;
        struct X4_ShotObj* shot;
        struct X4_MainObj* child;
    } object;
    const u8* script;
    struct X4_ShotObj* thruster;
    s16 background_unk1E;
    u8 saved_unk5;
    u8 hit_timer;
    u8 hit_active;
    u8 random_index;
    u8 orbs_ready;
    u8 bob_timer;
    s8 bob_step;
    u8 blink_delay;
};
#endif
#ifndef X4_D_Main8Ext
#define X4_D_Main8Ext
struct X4_Main8Ext {
    const void* unk80;
    const void* unk84;
    u8 unk88;
    u8 queued_sound;
    u8 unk8A;
    u8 unk8B;
    u8 unk8C;
};
#endif
#ifndef X4_D_Main9Ext
#define X4_D_Main9Ext
struct X4_Main9Ext {
    const u8* animation_1;
    const u8* animation_2;
    u8 animation_timer;
    u8 pad89[4];
    u8 object_id;
    u8 pad8E[2];
    struct X4_EffectObj* effect;
};
#endif
#ifndef X4_D_Main27Ext
#define X4_D_Main27Ext
struct X4_Main27Ext {
    u8 unk80;
    u8 collision_direction;
    u8 unk82;
    u8 pad83;
    s32 unk84;
    u8 unk88;
    u8 unk89;
    u8 unk8A;
    u8 unk8B;
    s32 unk8C;
    u8 unk90;
    u8 unk91;
    u8 unk92;
    u8 pad93;
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main28Ext
#define X4_D_Main28Ext
struct X4_Main28Ext {
    struct X4_MainObj* context;
    u8 unk84;
    u8 unk85;
    u16 unk86;
    u16 unk88;
    u16 index;
};
#endif
#ifndef X4_D_Main29Record
#define X4_D_Main29Record
struct X4_Main29Record {
    s8 unk0;
    s8 unk1;
    u8 pad2[2];
    s8 unk4;
};
#endif
#ifndef X4_D_Main29Ext
#define X4_D_Main29Ext
struct X4_Main29Ext {
    struct X4_MainObj* source;
    union {
        struct X4_MainObj* children[4];
        struct {
            struct X4_MainObj* children[2];
            struct X4_Main29Record* target;
            struct X4_Main29Record* record;
        } controller;
    } slots;
    u16 unk94;
    u16 unk96;
};
#endif
#ifndef X4_D_Main41Ext
#define X4_D_Main41Ext
struct X4_Main41Ext {
    u8 unk80;
    u8 pad81;
    u8 unk82;
    u8 unk83;
    u8 unk84;
};
#endif
#ifndef X4_D_Main42Ext
#define X4_D_Main42Ext
struct X4_Main42Ext {
    u8 background_relative;
    u8 pad81[3];
    struct X4_MiscObj* unk84;
};
#endif
#ifndef X4_D_Main68Ext
#define X4_D_Main68Ext
struct X4_Main68Ext {
    struct X4_MainObj* scythe;
    struct X4_VisualObj* visual;
    struct X4_EffectObj* effect;
    u8 count;
    u8 shot_type;
    u8 active_shots;
    u8 next_attack;
    u8 blink_delay;
    u8 flash_timer;
    s8 bob_step;
};
#endif
#ifndef X4_D_Main69State
#define X4_D_Main69State
union X4_Main69State {
    u32 word;
    struct {
        u8 variant;
        u8 unk8D;
        u8 unk8E;
        s8 wave_delay;
    } bytes;
};
#endif
#ifndef X4_D_Main69Ext
#define X4_D_Main69Ext
struct X4_Main69Ext {
    struct X4_EffectObj* effect;
    struct X4_VisualObj* linked_object;
    u8* script;
    union X4_Main69State state;
    u32 unk90;
    u32 unk94;
};
#endif
#ifndef X4_D_Main67Ext
#define X4_D_Main67Ext
struct X4_Main67Ext {
    s32 vertical_speed;
    s32 delay;
    u8 direction;
    u8 unk89;
    u8 unk8A;
    u8 pad8B[2];
    u8 unk8D;
    u8 pad8E[6];
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main66Ext
#define X4_D_Main66Ext
struct X4_Main66Ext {
    struct X4_EffectObj* effect;
    u8 drone_count;
    u8 hover_timer;
    u8 crystal_released;
    u8 release_countdown;
    u8 flash_timer;
    u8 trail_write;
    u8 trail_read;
    u8 trail_target;
    u8 active;
    u8 blink_timer;
    u8 pad8E[6];
    struct X4_MainObj* partner;
};
#endif
#ifndef X4_D_Main70Ext
#define X4_D_Main70Ext
struct X4_Main70Ext {
    s16 alarm_timer;
    s16 flash_timer;
    u8 pad84;
    u8 unk85;
    u8 alarm_color;
    u8 alarm_flashing;
    u8 pad88[0xC];
    u32 saved_unk5;
};
#endif
#ifndef X4_D_Main20Ext
#define X4_D_Main20Ext
struct X4_Main20Ext {
    s8 unk80;
    s8 unk81;
};
#endif
#ifndef X4_D_MainObjExt
#define X4_D_MainObjExt
union X4_MainObjExt {
    u32 raw[7];
    struct X4_Main0Ext main_0;
    struct X4_Main3Ext main_3;
    struct X4_Main5Ext main_5;
    struct X4_Main8Ext main_8;
    struct X4_Main9Ext main_9;
    struct X4_Main6Ext main_6;
    struct X4_Main7Ext main_7;
    struct X4_Main10Ext main_10;
    struct X4_Main11Ext main_11;
    struct X4_Main12Ext main_12;
    struct X4_Main13Ext main_13;
    struct X4_Main14Ext main_14;
    struct X4_Main16Ext main_16;
    struct X4_Main17Ext main_17;
    struct X4_Main18Ext main_18;
    struct X4_Main19Ext main_19;
    struct X4_Main20Ext main_20;
    struct X4_Main21Ext main_21;
    struct X4_Main22Ext main_22;
    struct X4_Main23Ext main_23;
    struct X4_Main26Ext main_26;
    struct X4_Main24Ext main_24;
    struct X4_Main25Ext main_25;
    struct X4_Main47Ext main_47;
    struct X4_Main27Ext main_27;
    struct X4_Main28Ext main_28;
    struct X4_Main29Ext main_29;
    struct X4_Main32Ext main_32;
    struct X4_Main33Ext main_33;
    struct X4_Main34Ext main_34;
    struct X4_Main35Ext main_35;
    struct X4_Main36Ext main_36;
    struct X4_Main41Ext main_41;
    struct X4_Main42Ext main_42;
    struct X4_Main43Ext main_43;
    struct X4_Main487Ext main_487;
    struct X4_Main37Ext main_37;
    struct X4_Main38Ext main_38;
    struct X4_Main39Ext main_39;
    struct X4_Main40Ext main_40;
    struct X4_MainSavedState94Ext main_44;
    struct X4_Main45Ext main_45;
    struct X4_Main48Ext main_48;
    struct X4_Main46Ext main_46;
    struct X4_Main49Ext main_49;
    struct X4_Main50Ext main_50;
    struct X4_Main51Ext main_51;
    struct X4_Main52Ext main_52;
    struct X4_Main54Ext main_54;
    struct X4_Main55Ext main_55;
    struct X4_Main56Ext main_56;
    struct X4_Main57Ext main_57;
    struct X4_Main58Ext main_58;
    struct X4_Main60Ext main_60;
    struct X4_Main61Ext main_61;
    struct X4_Main64Ext main_64;
    struct X4_Main65Ext main_65;
    struct X4_Main66Ext main_66;
    struct X4_Main67Ext main_67;
    struct X4_Main68Ext main_68;
    struct X4_Main69Ext main_69;
    struct X4_Main70Ext main_70;
    struct X4_Main53Ext main_53;
    struct X4_Main62Ext main_62;
    struct X4_Main71Ext main_71;
    struct X4_Main72Ext main_72;
    struct X4_Main73Ext main_73;
    struct X4_Main73PartsExt main_73_parts;
    struct X4_Main74Ext main_74;
    struct X4_Main75Ext main_75;
    struct X4_Main76Ext main_76;
};
#endif
#ifndef X4_D_MainObj
#define X4_D_MainObj
struct X4_MainObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17;
    X4_f32 unk18;
    X4_f32 unk1C;
    s32 x_speed; s32 y_speed; s32 x_accel; s32 gravity; const u8* const* animation_table; const u8* animation_cursor; s16 animation_speed; u8 pad3A[2]; const u8* sprite_frames; u16 unk40; u16 unk42; union X4_AnimationStep animation_step; u8 previous_animation_index; s8 pad49[2]; s8 unk4B; s8 pad4C[4]; const void* attack_box; const void* hurt_box; const void* collision_data; s8 hp; s8 unk5D; s8 unk5E; s8 unk5F; s8 contact_damage; s8 invincibility_timer; s8 unk62; s8 unk63; s8 unk64; s8 unk65; s8 unk66; s8 air_state; struct X4_Unk_unk68* terrain_box; s16 unk6C; s16 unk6E; u8 collision_flags; s8: 8; s8 unk72; s8 unk73; s8 unk74; s8 unk75; s8 unk76; s8 unk77; s8 unk78; s8 unk79; s8 unk7A; u8 unk7B; s16 unk7C; s16 unk7E; union X4_MainObjExt ext;
};
#endif
#ifndef X4_D_PlayerUnk88
#define X4_D_PlayerUnk88
union X4_PlayerUnk88 {
    u16 value;
    struct {
        s8 timer;
        u8 collision_flags;
    } bytes;
    struct {
        u8 timer;
        u8 collision_flags;
    } unsigned_bytes;
};
#endif
#ifndef X4_D_PlayerObj
#define X4_D_PlayerObj
struct X4_PlayerObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17; X4_f32 unk18; X4_f32 unk1C; X4_f32 x_vel; X4_f32 y_vel; s32 unk28; s32 unk2C; u32** animation_table; u32* animation_cursor; void* unk38; void* unk3C; u16 unk40; u16 unk42; union X4_AnimationStep animation_step; u8 previous_animation_index;
    s8 unk49;
    s8 wall_climbable;
    s8 pad4B[0x50 - 0x4B];
    void* unk50;
    const u32* unk54;
    void* unk58;
    s8 hp;
    s8 hud_hp;
    s8 unk5E;
    s8 unk5F;
    s8 unk60;
    s8 invincibility_timer;
    s8 unk62;
    s8 hurt_type;
    s8 unk64;
    s8 unk65;
    s8 unk66;
    s8 air_state;
    struct X4_Unk_unk68* unk68;
    s16 unk6C;
    s16 unk6E;
    u8 unk70;
    s8 unk71;
    u8 unk72;
    u8 unk73;
    u8 unk74;
    s8 unk75;
    s8 unk76;
    s8 unk77;
    s8 unk78;
    s8 touching_spikes;
    s8 spike_immune;
    union {
        u32 history;
        struct {
            u16 held;
            u16 previous;
        } buttons;
        struct {
            u8 held_low;
            u8 held_high;
            u8 previous_low;
            u8 previous_high;
        } bytes;
    } input;
    u16 pressed_input;
    u16 double_tap_direction;
    s8 dash_momentum;
    s8 dash_timer;
    s8 air_action;
    s8 double_tap_dash;
    union X4_PlayerUnk88 unk88;
    union X4_PlayerUnk8A unk8A;
    s8 afterimage;
    u8 unk8D;
    s8 attacking;
    s8 shot_fired;
    s8 attack_ended;
    u8 attack_pose_timer;
    u8 shot_cooldown;
    s8 weapon;
    s8 shot_types[2];
    s8 shot_type;
    s8 last_shot_type;
    s8 shot_count;
    s8 special_shot_count;
    s8 shot_cycle;
    X4_PlayerChargeState charge_state[2];
    u8 charge_timer;
    u8 special_charge_timer;
    s8 flash_delay;
    s8 flash_phase;
    s8 flash_palette;
    s8 shot_palette_timer;
    s8 : 8;
    s8 hurt_phase;
    s8 hit_facing;
    s8 stock_charge;
    s8 armor_parts;
    s8 weapon_energy[0x10];
    u8 arm_type;
    s8 boss_flags;
    s8 stun_timer;
    s8 combo;
    s8 update_delay;
    s8 update_delay_request;
    s8 beam_in_delay;
    s8 actions_reset;
    s8 script_state;
    s8 script_action;
    s8 script_facing;
    s8 input_locked;
    s8 capsule_state;
    s8 ride_state;
    s8 unkC6;
    s8 death_timer;
    struct X4_MainObj* weapon_06_slots[3];
    s8 ride_animation;
    u8 hover_timer;
    u8 hover_bob;
    s8 voice_timer;
    s8 : 8;
    s8 is_clone;
    u16 clone_timer;
    union X4_PlayerUnkDC clone_offset;
    s8 controlling_clone;
    s8 unkDF;
    s8 nova_strike_active;
    s8 nova_strike_timer;
    u8 item_step;
    s8 : 8;
};
#endif
#ifndef X4_D_Unk_unk68
#define X4_D_Unk_unk68
struct X4_Unk_unk68 {
    s8 unk0;
    s8 unk1;
    u8 unk2;
    u8 unk3;
};
#endif
#ifndef X4_D_VisualUnk5C
#define X4_D_VisualUnk5C
union X4_VisualUnk5C {
    s8 value;
    struct X4_PlayerObj* owner;
    struct {
        s8 pad5C;
        s8 mode;
        s16 unk5E;
    } fields;
};
#endif
#ifndef X4_D_VisualObj
#define X4_D_VisualObj
struct X4_VisualObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17; X4_f32 unk18; X4_f32 unk1C; X4_f32 x_vel; X4_f32 y_vel; s32 unk28; s32 unk2C; u32** animation_table; u32* animation_cursor; void* unk38; void* unk3C; u16 unk40; u16 unk42; union X4_AnimationStep animation_step; u8 previous_animation_index;
    u8 unk49;
    s8 pad4A[0x50 - 0x4A];
    struct X4_PlayerObj* unk50;
    s16 unk54;
    s16 unk56;
    s16 unk58;
    s16 unk5A;
    union X4_VisualUnk5C unk5C;
    u8 pa58[0x70 - 0x60];
};
#endif
#ifndef X4_D_Shot29Ext
#define X4_D_Shot29Ext
struct X4_Shot29Ext {
    u8 timer;
    u8 unk8D;
};
#endif
#ifndef X4_D_ShotUnk8C
#define X4_D_ShotUnk8C
union X4_ShotUnk8C {
    s32 word;
    struct X4_ShotObj* shot;
    u16 half;
    s16 halves[2];
    s8 byte;
    u8 bytes[4];
    struct X4_Shot29Ext shot_29;
    struct X4_ObjectHeader* object;
};
#endif
#ifndef X4_D_ShotUnk58
#define X4_D_ShotUnk58
union X4_ShotUnk58 {
    const u8* data;
    const u16* collision_data;
    const union X4_AnimationStep* animation_steps;
    struct X4_Unk_unk68* collision_bounds;
};
#endif
#ifndef X4_D_Shot24Ext
#define X4_D_Shot24Ext
struct X4_Shot24Ext {
    u8 owner_state;
    u8 owner_notified;
    s16 timer;
};
#endif
#ifndef X4_D_Shot55Unk84
#define X4_D_Shot55Unk84
struct X4_Shot55Unk84 {
    s16 x;
    s16 y;
};
#endif
#ifndef X4_D_ShotObj
#define X4_D_ShotObj
struct X4_ShotObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17; X4_f32 unk18; X4_f32 unk1C; X4_f32 x_vel; X4_f32 y_vel; s32 unk28; s32 unk2C; u32** animation_table; u32* animation_cursor; void* unk38; void* unk3C; u16 unk40; u16 unk42; union X4_AnimationStep animation_step; u8 previous_animation_index;
    s8 pad49[0x50 - 0x49];
    union {
        const u8* data;
        s16* frames;
        struct X4_PlayerObj* player;
    } unk50;
    const u8* unk54;
    union X4_ShotUnk58 unk58;
    s8 unk5C;
    s8 pad5D[0x60 - 0x5D];
    s8 unk60;
    s8 unk61;
    s8 unk62;
    s8 unk63;
    s8 unk64;
    s8 unk65;
    s8 unk66;
    s8 unk67;
    struct X4_Unk_unk68* unk68;
    s8 pad6C[0x70 - 0x6C];
    u8 unk70;
    s8 pad71;
    s8 unk72;
    s8 unk73;
    s8 unk74;
    s8 unk75;
    s8 unk76;
    s8 unk77;
    s8 unk78;
    s8 : 8;
    s8 unk7A;
    s8 : 8;
    struct X4_WeaponObj* unk7C;
    s32 : 32;
    union {
        s32 value;
        u32* collision_state;
        struct X4_EffectObj* effect;
        u16 halves[2];
        u8 bytes[4];
        struct X4_Shot24Ext shot_24;
        struct X4_Shot55Unk84 shot_55;
    } unk84;
    s16 timer;
    s16 unk8A;
    union X4_ShotUnk8C unk8C;
    X4_f32 unk90;
    s8 pad94;
    u8 unk95;
    s8 pad96[0x98 - 0x96];
    s8 unk98;
    s8 unk99;
    s8 pad9A[0x9C - 0x9A];
};
#endif
#ifndef X4_D_Weapon1Ext
#define X4_D_Weapon1Ext
struct X4_Weapon1Ext {
    u8 lifetime;
    u8 timer;
    u8 pad8E[0x90 - 0x8E];
    u8 unk90;
};
#endif
#ifndef X4_D_Weapon2Ext
#define X4_D_Weapon2Ext
struct X4_Weapon2Ext {
    u8 lifetime;
    u8 timer;
};
#endif
#ifndef X4_D_Weapon7Ext
#define X4_D_Weapon7Ext
struct X4_Weapon7Ext {
    u16 timer;
    u8 pad8E[2];
    u8 unk90;
    u8 unk91;
};
#endif
#ifndef X4_D_Weapon3Ext
#define X4_D_Weapon3Ext
struct X4_Weapon3Ext {
    u16 offset;
    u16 lifetime;
    s8 unk90;
    s8 unk91;
};
#endif
#ifndef X4_D_Weapon6Ext
#define X4_D_Weapon6Ext
struct X4_Weapon6Ext {
    u8 direction;
    u8 adjusted_direction;
    u8 lifetime;
    u8 timer;
};
#endif
#ifndef X4_D_Weapon8Ext
#define X4_D_Weapon8Ext
struct X4_Weapon8Ext {
    u8 timer;
};
#endif
#ifndef X4_D_Weapon17Ext
#define X4_D_Weapon17Ext
struct X4_Weapon17Ext {
    u8 pad8C;
    u8 timer;
};
#endif
#ifndef X4_D_Weapon10Ext
#define X4_D_Weapon10Ext
struct X4_Weapon10Ext {
    u8 timer;
    u8 pad8D[0x8F - 0x8D];
    u8 unk8F;
    u8 unk90;
};
#endif
#ifndef X4_D_Weapon14Ext
#define X4_D_Weapon14Ext
struct X4_Weapon14Ext {
    u8 unk8C;
    s8 unk8D;
};
#endif
#ifndef X4_D_Weapon13Ext
#define X4_D_Weapon13Ext
struct X4_Weapon13Ext {
    u8 timer;
};
#endif
#ifndef X4_D_Weapon16Ext
#define X4_D_Weapon16Ext
struct X4_Weapon16Ext {
    u16 timer;
    u16 delay;
    u8 pad90;
    u8 unk91;
};
#endif
#ifndef X4_D_Weapon20Ext
#define X4_D_Weapon20Ext
struct X4_Weapon20Ext {
    u8 lifetime;
    u8 timer;
    s8 unk8E;
};
#endif
#ifndef X4_D_WeaponUnk84
#define X4_D_WeaponUnk84
union X4_WeaponUnk84 {
    s32 word;
    u8 byte;
    u8 bytes[4];
    u16 halves[2];
};
#endif
#ifndef X4_D_Weapon15Ext
#define X4_D_Weapon15Ext
struct X4_Weapon15Ext {
    u8 unk8C;
    u8 unk8D;
    u8 unk8E;
    u8 unk8F;
};
#endif
#ifndef X4_D_WeaponUnk88
#define X4_D_WeaponUnk88
union X4_WeaponUnk88 {
    u16 half;
    u8 bytes[2];
};
#endif
#ifndef X4_D_WeaponUnk80
#define X4_D_WeaponUnk80
union X4_WeaponUnk80 {
    s32 word;
    u8 bytes[4];
};
#endif
#ifndef X4_D_Weapon29Ext
#define X4_D_Weapon29Ext
struct X4_Weapon29Ext {
    u8 pad8C[4];
    s32 unk90;
};
#endif
#ifndef X4_D_Shot46Ext
#define X4_D_Shot46Ext
struct X4_Shot46Ext {
    u8 unk8C;
    u8 pad8D;
    u8 unk8E;
    u8 unk8F;
};
#endif
#ifndef X4_D_Shot55Ext
#define X4_D_Shot55Ext
struct X4_Shot55Ext {
    u8 pad8C[0x90 - 0x8C];
    u8 unk90;
    u8 pad91;
    u8 unk92;
};
#endif
#ifndef X4_D_Weapon60Ext
#define X4_D_Weapon60Ext
struct X4_Weapon60Ext {
    struct X4_MainObj* target;
    u8 direction;
};
#endif
#ifndef X4_D_WeaponObjExt
#define X4_D_WeaponObjExt
union X4_WeaponObjExt {
    u8 raw[0x94 - 0x8C];
    X4_RECT* rect;
    struct X4_MainObj* target;
    struct X4_Weapon1Ext weapon_1;
    struct X4_Weapon2Ext weapon_2;
    struct X4_Weapon6Ext weapon_6;
    struct X4_Weapon3Ext weapon_3;
    struct X4_Weapon7Ext weapon_7;
    struct X4_Weapon8Ext weapon_8;
    struct X4_Weapon10Ext weapon_10;
    struct X4_Weapon14Ext weapon_14;
    struct X4_Weapon13Ext weapon_13;
    struct X4_Weapon15Ext weapon_15;
    struct X4_Weapon16Ext weapon_16;
    struct X4_Weapon60Ext weapon_60;
    struct X4_Weapon17Ext weapon_17;
    struct X4_Weapon20Ext weapon_20;
    struct X4_Weapon29Ext weapon_29;
    struct X4_Shot46Ext shot_46;
    struct X4_Shot55Ext shot_55;
};
#endif
#ifndef X4_D_WeaponObj
#define X4_D_WeaponObj
struct X4_WeaponObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17;
    X4_f32 unk18;
    X4_f32 unk1C;
    X4_f32 x_vel;
    X4_f32 y_vel;
    X4_f32 unk28;
    s32 unk2C;
    u32** animation_table;
    u32* animation_cursor;
    void* unk38;
    void* unk3C;
    u16 unk40;
    u16 unk42;
    union X4_AnimationStep animation_step;
    u8 previous_animation_index;
    s8 unk49;
    s8 pad4A[0x50 - 0x4A];
    const void* unk50;
    const void* unk54;
    const void* unk58;
    s8 unk5C;
    s8 pad5D[3];
    s8 unk60;
    s8 unk61;
    s8 unk62;
    s8 unk63;
    s8 unk64;
    s8 unk65;
    s8 unk66;
    s8 unk67;
    struct X4_Unk_unk68* unk68;
    s8 pad6C[4];
    u8 unk70;
    s8 unk71;
    u8 unk72;
    s8 unk73;
    s8 unk74;
    s8 unk75;
    s8 unk76;
    s8 unk77;
    s8 unk78;
    s8 : 8;
    s8 unk7A;
    s8 pad7B;
    struct X4_PlayerObj* owner;
    union X4_WeaponUnk80 unk80;
    union X4_WeaponUnk84 unk84;
    union X4_WeaponUnk88 unk88;
    s8 pad8A[0x8C - 0x8A];
    union X4_WeaponObjExt ext;
    u8 unk94;
    u8 unk95;
    s8 pad96[0x98 - 0x96];
    s8 unk98;
    s8 pad99[0x9C - 0x99];
};
#endif
#ifndef X4_D_Item2Ext
#define X4_D_Item2Ext
struct X4_Item2Ext {
    s8 unk80;
    s8 unk81;
    u16 unk82;
};
#endif
#ifndef X4_D_Item12Ext
#define X4_D_Item12Ext
struct X4_Item12Ext {
    s32 x_offset;
};
#endif
#ifndef X4_D_Item23Ext
#define X4_D_Item23Ext
struct X4_Item23Ext {
    s16 unk80;
    s16 timer;
};
#endif
#ifndef X4_D_Item22Ext
#define X4_D_Item22Ext
struct X4_Item22Ext {
    s32 collision_side;
};
#endif
#ifndef X4_D_ItemExt
#define X4_D_ItemExt
union X4_ItemExt {
    u32 packed;
    s32 timer;
    struct X4_Item2Ext item_2;
    struct X4_Item12Ext item_12;
    struct X4_Item22Ext item_22;
    struct X4_Item23Ext item_23;
    struct X4_MainObj* owner;
};
#endif
#ifndef X4_D_ItemUnk84
#define X4_D_ItemUnk84
union X4_ItemUnk84 {
    u16 timer;
    u32 previous_value;
    u8 bytes[4];
};
#endif
#ifndef X4_D_ItemUnk7C
#define X4_D_ItemUnk7C
union X4_ItemUnk7C {
    u8 value;
    u16 timer16;
    s32 timer;
    struct X4_MainObj* owner;
    struct X4_MiscObj* misc;
    void* object;
    struct X4_Unk_unk68* bounds;
    s32 item_26_value;
};
#endif
#ifndef X4_D_ItemTailExtUnk
#define X4_D_ItemTailExtUnk
struct X4_ItemTailExtUnk {
    union X4_ItemUnk84 unk84;
    s32 unk88;
};
#endif
#ifndef X4_D_ItemTailExtUnk2
#define X4_D_ItemTailExtUnk2
struct X4_ItemTailExtUnk2 {
    u8 timer;
    u8 previous_value;
    u8 value;
};
#endif
#ifndef X4_D_ItemTailExt
#define X4_D_ItemTailExt
union X4_ItemTailExt {
    struct X4_ItemTailExtUnk unk1;
    struct X4_ItemTailExtUnk2 unk2;
};
#endif
#ifndef X4_D_ItemObj
#define X4_D_ItemObj
struct X4_ItemObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17;
    X4_f32 unk18;
    X4_f32 unk1C;
    X4_f32 x_vel;
    X4_f32 y_vel;
    s32 unk28;
    s32 unk2C;
    const u8* const* animation_table;
    const u8* animation_cursor;
    s16 animation_speed;
    u8 pad3A[2];
    const u8* sprite_frames;
    u16 unk40;
    u16 unk42;
    union X4_AnimationStep animation_step;
    u8 previous_animation_index;
    s8 pad49[0x50 - 0x49];
    const u8* unk50;
    const u8* unk54;
    const u8* unk58;
    s8 unk5C;
    s8 pad5D[0x61 - 0x5D];
    s8 unk61;
    s8 unk62;
    s8 unk63;
    s8 unk64;
    s8 unk65;
    s8 unk66;
    s8 unk67;
    struct X4_Unk_unk68* unk68;
    s8 pad6C[0x70 - 0x6C];
    u8 unk70;
    s8 : 8;
    s8 unk72;
    s8 unk73;
    s8 unk74;
    s8 unk75;
    s8 unk76;
    s8 unk77;
    s8 unk78;
    s8 : 8;
    s8 unk7A;
    s8 pad7B;
    union X4_ItemUnk7C unk7C;
    union X4_ItemExt ext;
    union X4_ItemTailExt tail_ext;
};
#endif
#ifndef X4_D_LayerPrivateState
#define X4_D_LayerPrivateState
union X4_LayerPrivateState {
    X4_f32 value;
    s8 signed_byte;
    u8 misc_20_active;
};
#endif
#ifndef X4_D_LayerObj
#define X4_D_LayerObj
struct X4_LayerObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17;
    X4_f32 unk18;
    union X4_LayerPrivateState private_state;
    s8 pad20[0x24 - 0x20];
    u8 unk24;
    u8 unk25;
    s8 pad26[0x30 - 0x26];
};
#endif
#ifndef X4_D_MiscUnk50_2
#define X4_D_MiscUnk50_2
struct X4_MiscUnk50_2 {
    s8 unk0;
    s8 pad_[4];
    X4_f32 x_pos;
    X4_f32 y_pos;
    s32 unk8;
    s32 unkC;
    u8 unk16;
};
#endif
#ifndef X4_D_ReadyTextExt
#define X4_D_ReadyTextExt
struct X4_ReadyTextExt {
    struct X4_EffectObj* owner;
    u16 unk54;
    u16 stay_up_timer;
    u16 palette_pos;
    u16 unk58;
    u16 palette_cycle_done;
};
#endif
#ifndef X4_D_MiscPointerExt
#define X4_D_MiscPointerExt
struct X4_MiscPointerExt {
    void* unk50;
};
#endif
#ifndef X4_D_Misc7Ext
#define X4_D_Misc7Ext
struct X4_Misc7Ext {
    void* position;
};
#endif
#ifndef X4_D_Misc5Ext
#define X4_D_Misc5Ext
struct X4_Misc5Ext {
    struct X4_MainObj* owner;
    s8 animation;
};
#endif
#ifndef X4_D_Misc8Ext
#define X4_D_Misc8Ext
struct X4_Misc8Ext {
    u8 pad50[4];
    u8 alternate;
    u8 timer;
};
#endif
#ifndef X4_D_Misc2Ext
#define X4_D_Misc2Ext
struct X4_Misc2Ext {
    u8 pad50[4];
    struct X4_MainObj* owner;
    u8 unk58;
};
#endif
#ifndef X4_D_Misc9Ext
#define X4_D_Misc9Ext
struct X4_Misc9Ext {
    u8 pad50[4];
    struct X4_ItemObj* owner;
    u8 unk58;
};
#endif
#ifndef X4_D_Misc11Ext
#define X4_D_Misc11Ext
struct X4_Misc11Ext {
    u8 pad50[4];
    s8 active;
};
#endif
#ifndef X4_D_Misc42Ext
#define X4_D_Misc42Ext
struct X4_Misc42Ext {
    u8 pad50[4];
    s8 unk54;
    s8 unk55;
    s8 unk56;
    s8 unk57;
};
#endif
#ifndef X4_D_Misc15Ext
#define X4_D_Misc15Ext
struct X4_Misc15Ext {
    u8 pad50[4];
    u16 unk54;
};
#endif
#ifndef X4_D_Misc16Ext
#define X4_D_Misc16Ext
struct X4_Misc16Ext {
    u8 pad50[4];
    u16 timer;
};
#endif
#ifndef X4_D_Misc51Ext
#define X4_D_Misc51Ext
struct X4_Misc51Ext {
    struct X4_MainObj* source;
    u8 unk54;
};
#endif
#ifndef X4_D_Misc49Ext
#define X4_D_Misc49Ext
struct X4_Misc49Ext {
    void* owner;
    u16 timer;
};
#endif
#ifndef X4_D_Misc45Ext
#define X4_D_Misc45Ext
struct X4_Misc45Ext {
    u8 pad50[4];
    struct X4_MainObj* owner;
    s16 unk58;
    s16 target_x;
    u8 direction;
};
#endif
#ifndef X4_D_Misc24Ext
#define X4_D_Misc24Ext
struct X4_Misc24Ext {
    struct X4_MainObj* main;
    s16 timer;
    u16 child_active;
    struct X4_MiscObj* child;
};
#endif
#ifndef X4_D_TitleLogoExt
#define X4_D_TitleLogoExt
struct X4_TitleLogoExt {
    struct X4_MiscObj* unk50;
    u8 palette_shift_speed;
    u8 palette_shift_value;
    s8 unk56;
    u8 unk57;
    s32* palette1;
    s32* palette2;
};
#endif
#ifndef X4_D_SelectACharacterExt
#define X4_D_SelectACharacterExt
struct X4_SelectACharacterExt {
    s8 pad50[4];
    s8 unk54;
    u8 blast_timer;
    s8 unk56;
    u8 cur_character_selected;
};
#endif
#ifndef X4_D_Misc4Ext
#define X4_D_Misc4Ext
struct X4_Misc4Ext {
    struct X4_MainObj* owner;
};
#endif
#ifndef X4_D_Misc6Ext
#define X4_D_Misc6Ext
struct X4_Misc6Ext {
    u8 pad50[4];
    union {
        s32 packed;
        struct {
            s16 x;
            s16 y;
        } position;
    } saved_position;
    u8 timer;
};
#endif
#ifndef X4_D_Misc20Ext
#define X4_D_Misc20Ext
struct X4_Misc20Ext {
    struct X4_LayerObj* owner;
};
#endif
#ifndef X4_D_Misc31Ext
#define X4_D_Misc31Ext
struct X4_Misc31Ext {
    u8 pad50[4], animation;
};
#endif
#ifndef X4_D_Misc33Ext
#define X4_D_Misc33Ext
struct X4_Misc33Ext {
    s8* completion_flag;
    u16 timer;
};
#endif
#ifndef X4_D_Misc34Ext
#define X4_D_Misc34Ext
struct X4_Misc34Ext {
    struct X4_EffectObj* related;
    u8 timer;
    u8 pad55;
    u8 variant;
    u8 unk57;
    u8 unk58;
    u8 enabled;
    u16 unk5A;
    u8 unk5C;
    u8 unk5D;
};
#endif
#ifndef X4_D_Misc39Ext
#define X4_D_Misc39Ext
struct X4_Misc39Ext {
    void* related;
    s16 timer;
};
#endif
#ifndef X4_D_Misc55Ext
#define X4_D_Misc55Ext
struct X4_Misc55Ext {
    struct X4_MainObj* owner;
};
#endif
#ifndef X4_D_Misc52Ext
#define X4_D_Misc52Ext
struct X4_Misc52Ext {
    u8 pad50[5];
    u8 timer;
    u8 unk56;
    s8 unk57;
};
#endif
#ifndef X4_D_Misc22Ext
#define X4_D_Misc22Ext
struct X4_Misc22Ext {
    struct X4_MainObj* owner;
    u8 pad54[2];
    u8 timer;
};
#endif
#ifndef X4_D_Misc26Ext
#define X4_D_Misc26Ext
struct X4_Misc26Ext {
    struct X4_MainObj* owner;
    u8 timer;
};
#endif
#ifndef X4_D_Misc30Ext
#define X4_D_Misc30Ext
struct X4_Misc30Ext {
    struct X4_MainObj* owner;
    s8 unk54;
    u8 pad55;
    s16 unk56;
};
#endif
#ifndef X4_D_Misc53Ext
#define X4_D_Misc53Ext
struct X4_Misc53Ext {
    u8 pad50[4];
    struct X4_EffectObj* effect;
    s16 timer;
    u8 movement_timer;
    u8 pad5B;
    s8 x_step;
};
#endif
#ifndef X4_D_UnkExt
#define X4_D_UnkExt
struct X4_UnkExt {
    struct X4_MiscUnk50_2* unk50;
    s8 unk54;
    s8 unk55;
    union {
        s8 byte;
        u16 sht;
    } unk56;
};
#endif
#ifndef X4_D_MiscExt
#define X4_D_MiscExt
union X4_MiscExt {
    struct X4_Misc2Ext misc_2;
    struct X4_Misc9Ext misc_9;
    struct X4_Misc5Ext misc_5;
    struct X4_Misc7Ext misc_7;
    struct X4_Misc8Ext misc_8;
    struct X4_Misc11Ext misc_11;
    struct X4_Misc15Ext misc_15;
    struct X4_Misc16Ext misc_16;
    struct X4_Misc42Ext misc_42;
    struct X4_Misc45Ext misc_45;
    struct X4_Misc51Ext misc_51;
    struct X4_Misc49Ext misc_49;
    struct X4_Misc24Ext misc_24;
    struct X4_ReadyTextExt ready_text;
    struct X4_MiscPointerExt pointer;
    struct X4_TitleLogoExt title_logo;
    struct X4_SelectACharacterExt sel_char;
    struct X4_Misc4Ext misc_4;
    struct X4_Misc6Ext misc_6;
    struct X4_Misc20Ext misc_20;
    struct X4_Misc31Ext misc_31;
    struct X4_Misc33Ext misc_33;
    struct X4_Misc34Ext misc_34;
    struct X4_Misc39Ext misc_39;
    struct X4_Misc52Ext misc_52;
    struct X4_Misc22Ext misc_22;
    struct X4_Misc30Ext misc_30;
    struct X4_Misc26Ext misc_26;
    struct X4_Misc53Ext misc_53;
    struct X4_Misc55Ext misc_55;
    struct X4_UnkExt unk;
};
#endif
#ifndef X4_D_MiscObj
#define X4_D_MiscObj
struct X4_MiscObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17; X4_f32 unk18; X4_f32 unk1C; X4_f32 x_vel; X4_f32 y_vel; s32 unk28; s32 unk2C; u32** animation_table; u32* animation_cursor; void* unk38; void* unk3C; u16 unk40; u16 unk42; union X4_AnimationStep animation_step; u8 previous_animation_index;
    s8 pad49[4];
    union X4_MiscExt ext;
};
#endif
#ifndef X4_D_EngineCharacterState
#define X4_D_EngineCharacterState
union X4_EngineCharacterState {
    s8 bytes[0x10];
    struct {
        s8 active;
        s8 flags;
        s8 selected_characters;
        s8 previous_character;
        s8 secret_code_phase;
        s8 secret_code_index;
        s32 menu_state;
        u8 reserved[6];
    } __attribute__((packed)) fields;
};
#endif
#ifndef X4_D_EngineObj
#define X4_D_EngineObj
struct X4_EngineObj {
    s8 state;
    s8 unk1;
    s8 unk2;
    s8 unk3;
    s16 unk4;
    s8 unk6;
    s8 unk7;
    s16 unk8;
    s16 unkA;
    s8 stage;
    s8 substage;
    s8 unkE;
    s8 unkF;
    s8 unk10;
    s8 unk11;
    s8 unk12;
    s8 unk13;
    s8 unk14;
    s8 unk15;
    s8 unk16;
    s8 unk17;
    s8 unk18;
    s8 unk19;
    s8 unk1A;
    s8 unk1B;
    s8 unk1C;
    s8 checkpoint;
    s8 unk1E;
    s8 unk1F;
    struct X4_MainObj* boss_ptr;
    s8 enable_boss;
    s8 unk25;
    union X4_EngineCharacterState character_state;
    union {
        s8 value;
        u8 timer;
    } unk36;
    s8 unk37;
    void* unk38;
    struct X4_BaseObj* unk3C;
    u8 unk40;
    s8 unk41;
    u8 unk42;
    s8 cur_character;
    s8 unk44;
    u8 unk45;
    s8 unk46;
    s8 unk47;
    s8 unk48;
    s8 player_initial_data[0x10];
    s8 palette_flags;
    u16 unk5A;
    s8 unk5C[3];
    u8 unk5F;
    u8 unk60;
    u8 pad61[3];
};
#endif
#ifndef X4_D_Unk14
#define X4_D_Unk14
struct X4_Unk14 {
    u16 unk0;
    s8 unk2;
    u8 unk3;
};
#endif
#ifndef X4_D_UnkEffectExt
#define X4_D_UnkEffectExt
struct X4_UnkEffectExt {
    u8 unk14;
    u8 unk15;
    u8 unk16;
    s8 : 8;
    void* unk18;
};
#endif
#ifndef X4_D_Effect26Ext
#define X4_D_Effect26Ext
struct X4_Effect26Ext {
    u16 timer;
    u8 quad_timer;
};
#endif
#ifndef X4_D_Effect4Ext
#define X4_D_Effect4Ext
struct X4_Effect4Ext {
    u16 timer;
    s16 unk16;
};
#endif
#ifndef X4_D_Effect22Ext
#define X4_D_Effect22Ext
struct X4_Effect22Ext {
    u8 unk14;
    u8 unk15;
    s8 unk16;
    s8 unk17;
    s16 unk18;
};
#endif
#ifndef X4_D_Effect24Ext
#define X4_D_Effect24Ext
struct X4_Effect24Ext {
    struct X4_EffectObj* spawned_effect;
    u16 timer;
    u8 unk1A;
    u8 unk1B;
};
#endif
#ifndef X4_D_Effect12Ext
#define X4_D_Effect12Ext
struct X4_Effect12Ext {
    struct X4_MainObj* children[4];
    u16 cooldown;
    u16 timer;
    u8 spawned;
    u8 child_count;
    u8 child_subtype;
    u8 child_id;
};
#endif
#ifndef X4_D_Effect16Ext
#define X4_D_Effect16Ext
struct X4_Effect16Ext {
    u8 pad14[4];
    u16 saved_background_2A;
    u16 saved_background_28;
};
#endif
#ifndef X4_D_Effect38Ext
#define X4_D_Effect38Ext
struct X4_Effect38Ext {
    u8 pad14;
    u8 timer;
    u8 active;
    u8 variant;
};
#endif
#ifndef X4_D_Effect28Ext
#define X4_D_Effect28Ext
struct X4_Effect28Ext {
    u8 pad14[4];
    u8 timer;
    u8 filter_timer;
    u8 pad1A;
    u8 unk1B;
    u8 palette_index;
    u8 finished;
};
#endif
#ifndef X4_D_Effect37Ext
#define X4_D_Effect37Ext
struct X4_Effect37Ext {
    u8 pad14[4];
    u8 timer;
    u8 unk19;
    u8 pad1A[2];
    u8 action;
    u8 finished;
    u8 unk1E;
    u8 unk1F;
    u8 unk20;
    u8 unk21;
    u8 unk22;
};
#endif
#ifndef X4_D_Effect34Ext
#define X4_D_Effect34Ext
struct X4_Effect34Ext {
    u8 unk14;
    u8 pad15;
    u16 timer;
};
#endif
#ifndef X4_D_Effect8Ext
#define X4_D_Effect8Ext
struct X4_Effect8Ext {
    u8 pad14[2];
    s8 unk16;
    s8 unk17;
    s16 unk18;
};
#endif
#ifndef X4_D_Effect9Ext
#define X4_D_Effect9Ext
struct X4_Effect9Ext {
    s16 transition_timer;
    u16 movement_timer;
    s16 direction;
    u16 target_x;
    u8* movement_table;
    u8 timer;
    s8 frame;
    u8 pad22[2];
    s32 velocity;
};
#endif
#ifndef X4_D_Effect42Ext
#define X4_D_Effect42Ext
struct X4_Effect42Ext {
    union {
        struct X4_MainObj* main;
        struct X4_PlayerObj* player;
    } owner;
    u8 timer;
};
#endif
#ifndef X4_D_Effect43Ext
#define X4_D_Effect43Ext
struct X4_Effect43Ext {
    u16 unk14;
    u16 unk16;
};
#endif
#ifndef X4_D_Effect21SpawnRecord
#define X4_D_Effect21SpawnRecord
struct X4_Effect21SpawnRecord {
    u16 x;
    u16 y;
    u8 object_id;
    u8 flags;
};
#endif
#ifndef X4_D_Effect21Ext
#define X4_D_Effect21Ext
struct X4_Effect21Ext {
    struct X4_Effect21SpawnRecord* cursor;
    u32 spawned;
    u8 timer;
    u8 index;
    u8 phase;
    u8 inside;
    u8 was_inside;
};
#endif
#ifndef X4_D_Effect5Ext
#define X4_D_Effect5Ext
struct X4_Effect5Ext {
    s32 unk14;
    s32 unk18;
    u8 unk1C;
    u8 unk1D;
    u8 unk1E;
    u8 unk1F;
    u8 unk20;
    u8 unk21;
};
#endif
#ifndef X4_D_Effect14Ext
#define X4_D_Effect14Ext
struct X4_Effect14Ext {
    u16 unk14;
    u8 unk16;
};
#endif
#ifndef X4_D_Effect17Ext
#define X4_D_Effect17Ext
struct X4_Effect17Ext {
    struct X4_AnimatedObj* source;
    u8 timer;
    u8 phase;
};
#endif
#ifndef X4_D_Effect32Palette
#define X4_D_Effect32Palette
union X4_Effect32Palette {
    s32 packed;
    struct {
        u8 timer;
        u8 unk1;
        s8 step;
        u8 id;
    } fields;
};
#endif
#ifndef X4_D_Effect32PaletteSource
#define X4_D_Effect32PaletteSource
union X4_Effect32PaletteSource {
    u8* bytes;
    s32* words;
    struct X4_Effect28AnimationStep* animation;
};
#endif
#ifndef X4_D_Effect32Ext
#define X4_D_Effect32Ext
struct X4_Effect32Ext {
    u8 unk14;
    s8 unk15;
    u8 unk16, pad17;
    union X4_Effect32Palette palette;
    union X4_Effect32PaletteSource palette_source;
};
#endif
#ifndef X4_D_Effect33Ext
#define X4_D_Effect33Ext
struct X4_Effect33Ext {
    u8 timer;
    u8 period;
    u8 proximity;
    u8 variant;
    u8 burst;
    u8 cooldown;
};
#endif
#ifndef X4_D_EffectPaletteExt
#define X4_D_EffectPaletteExt
struct X4_EffectPaletteExt {
    u8 unk14, unk15, unk16, pad17;
    union X4_Effect32Palette palette;
    union X4_Effect32PaletteSource palette_source;
};
#endif
#ifndef X4_D_Effect23Ext
#define X4_D_Effect23Ext
struct X4_Effect23Ext {
    u32 unk14;
    union X4_Effect32Palette palette;
    union X4_Effect32PaletteSource palette_source;
};
#endif
#ifndef X4_D_Effect41Ext
#define X4_D_Effect41Ext
struct X4_Effect41Ext {
    u32 unk14;
    union X4_Effect32Palette palette;
    union X4_Effect32PaletteSource palette_source;
};
#endif
#ifndef X4_D_Effect36Ext
#define X4_D_Effect36Ext
struct X4_Effect36Ext {
    u8 pad14[4];
    struct X4_EffectObj* spawned_effect;
    u32 timer;
};
#endif
#ifndef X4_D_Effect28AnimationStep
#define X4_D_Effect28AnimationStep
struct X4_Effect28AnimationStep {
    u8 timer;
    u8 unused;
    s8 frame_step;
    u8 frame;
};
#endif
#ifndef X4_D_ScalingX
#define X4_D_ScalingX
struct X4_ScalingX {
    struct X4_Unk14* unk14;
    s8 unk18;
};
#endif
#ifndef X4_D_PaletteAnimationExt
#define X4_D_PaletteAnimationExt
struct X4_PaletteAnimationExt {
    s32* source;
    s32* destination;
    s8* cursor;
    s8 palette_count;
    s8 timer;
    u8 padding[14];
};
#endif
#ifndef X4_D_EffectExt
#define X4_D_EffectExt
union X4_EffectExt {
    struct X4_Effect12Ext effect_12;
    struct X4_Effect16Ext effect_16;
    struct X4_Effect9Ext effect_9;
    struct X4_Effect26Ext effect_26;
    struct X4_Effect4Ext effect_4;
    struct X4_UnkEffectExt unk_effect;
    struct X4_Effect5Ext effect_5;
    struct X4_Effect21Ext effect_21;
    struct X4_Effect8Ext effect_8;
    struct X4_Effect14Ext effect_14;
    struct X4_Effect17Ext effect_17;
    struct X4_UnkEffectExt effect_15;
    struct X4_UnkEffectExt effect_19;
    struct X4_UnkEffectExt effect_20;
    struct X4_Effect22Ext effect_22;
    struct X4_Effect24Ext effect_24;
    struct X4_UnkEffectExt effect_25;
    struct X4_UnkEffectExt effect_27;
    struct X4_Effect23Ext effect_23;
    struct X4_Effect28Ext effect_28;
    struct X4_EffectPaletteExt effect_29;
    struct X4_Effect32Ext effect_32;
    struct X4_Effect33Ext effect_33;
    struct X4_Effect34Ext effect_34;
    struct X4_Effect36Ext effect_36;
    struct X4_Effect37Ext effect_37;
    struct X4_Effect38Ext effect_38;
    struct X4_EffectPaletteExt effect_39;
    struct X4_EffectPaletteExt effect_40;
    struct X4_Effect41Ext effect_41;
    struct X4_Effect42Ext effect_42;
    struct X4_Effect43Ext effect_43;
    struct X4_ScalingX scaling_x;
    struct X4_PaletteAnimationExt palette_animation;
};
#endif
#ifndef X4_D_EffectObj
#define X4_D_EffectObj
struct X4_EffectObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref;
    union X4_EffectExt ext;
};
#endif
#ifndef X4_D_RideArmorUnkA0
#define X4_D_RideArmorUnkA0
union X4_RideArmorUnkA0 {
    struct {
        s16 x;
        s16 y;
    } saved_accel;
    struct X4_EffectObj* chaser_effect;
};
#endif
#ifndef X4_D_RideArmorUnk98
#define X4_D_RideArmorUnk98
union X4_RideArmorUnk98 {
    s16 packed;
    struct {
        u8 low;
        u8 high;
    } bytes;
};
#endif
#ifndef X4_D_RideArmorUnk80
#define X4_D_RideArmorUnk80
union X4_RideArmorUnk80 {
    u32 packed;
    struct {
        u8 unk80;
        u8 unk81;
        u8 unk82;
        u8 unk83;
    } bytes;
};
#endif
#ifndef X4_D_RideArmorUnk94
#define X4_D_RideArmorUnk94
union X4_RideArmorUnk94 {
    u32 value;
    u16 halves[2];
    struct {
        u8 pad94[3];
        s8 unk97;
    } bytes;
};
#endif
#ifndef X4_D_RideArmorUnk90
#define X4_D_RideArmorUnk90
union X4_RideArmorUnk90 {
    u32 value;
    s8 byte;
    struct {
        u8 pad90[3];
        u8 action_state;
    } bytes;
};
#endif
#ifndef X4_D_RideArmorInputState
#define X4_D_RideArmorInputState
union X4_RideArmorInputState {
    u16 value;
    struct {
        u8 buttons;
        u8 cooldown;
    } bytes;
};
#endif
#ifndef X4_D_RideArmorTapState
#define X4_D_RideArmorTapState
union X4_RideArmorTapState {
    u16 value;
    struct {
        u8 active;
        u8 timer;
    } bytes;
};
#endif
#ifndef X4_D_RideArmorObj
#define X4_D_RideArmorObj
struct X4_RideArmorObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17; X4_f32 unk18; X4_f32 unk1C; X4_f32 x_vel; X4_f32 y_vel; s32 unk28; s32 unk2C; u32** animation_table; u32* animation_cursor; void* unk38; void* unk3C; u16 unk40; u16 unk42; union X4_AnimationStep animation_step; u8 previous_animation_index;
    s8 unk49;
    s8 unk4A;
    s8 pad4B[0x50 - 0x4B];
    void* unk50;
    const void* unk54;
    const void* unk58;
    s8 unk5C;
    s8 unk5D;
    s8 unk5E;
    s8 unk5F;
    s8 unk60;
    s8 unk61;
    s8 unk62;
    s8 unk63;
    s8 unk64;
    s8 unk65;
    s8 unk66;
    s8 unk67;
    struct X4_Unk_unk68* unk68;
    s16 unk6C;
    s16 unk6E;
    u8 unk70;
    u8 unk71;
    u8 unk72;
    u8 unk73;
    u8 unk74;
    s8 unk75;
    s8 unk76;
    s8 unk77;
    s8 unk78;
    s8 unk79;
    s8 unk7A;
    s8 pad7B;
    u8 unk7C;
    u8 unk7D;
    u8 unk7E;
    u8 spawned_parts;
    union X4_RideArmorUnk80 unk80;
    u8 unk84;
    u8 unk85;
    u8 unk86;
    s8 pad87;
    u16 collision_flags;
    s16 unk8A;
    union X4_RideArmorInputState unk8C;
    union X4_RideArmorTapState unk8E;
    union X4_RideArmorUnk90 unk90;
    union X4_RideArmorUnk94 unk94;
    union X4_RideArmorUnk98 unk98;
    s16 pad9A;
    s16 saved_x_vel;
    s16 saved_y_vel;
    union X4_RideArmorUnkA0 unkA0;
    s16 launch_speed;
    u16 unkA6;
    s8 input_flags;
    s8 padA9[0xB0 - 0xA9];
};
#endif
#ifndef X4_D_AbcObj
#define X4_D_AbcObj
struct X4_AbcObj {
    u16* unk0;
    u16 unk4;
    s16 unk6;
    s16 unk8;
    u16 unkA;
    u8 unkC;
    u8 unkD;
    u8 unkE;
    u8 unkF;
    s16 unk10;
    s16 : 16;
};
#endif
#ifndef X4_D_UnkObjLink
#define X4_D_UnkObjLink
union X4_UnkObjLink {
    u8* data;
    struct X4_UnkObj* previous;
    struct X4_PlayerObj* player;
};
#endif
#ifndef X4_D_PlayerAfterimageExt
#define X4_D_PlayerAfterimageExt
struct X4_PlayerAfterimageExt {
    s16 position_timer;
    s16 blink_timer;
    s16 palette_offset;
    u8 pad5A[6];
};
#endif
#ifndef X4_D_Unk0Ext
#define X4_D_Unk0Ext
struct X4_Unk0Ext {
    u8 selection_index;
};
#endif
#ifndef X4_D_UnkObjExt
#define X4_D_UnkObjExt
union X4_UnkObjExt {
    u8 raw[0xC];
    s8 timer;
    struct X4_Unk0Ext unk_0;
    struct X4_PlayerAfterimageExt afterimage;
};
#endif
#ifndef X4_D_UnkObj
#define X4_D_UnkObj
struct X4_UnkObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17; X4_f32 unk18; X4_f32 unk1C; X4_f32 x_vel; X4_f32 y_vel; s32 unk28; s32 unk2C; u32** animation_table; u32* animation_cursor; void* unk38; void* unk3C; u16 unk40; u16 unk42; union X4_AnimationStep animation_step; u8 previous_animation_index;
    s8 pad49[0x4B - 0x49];
    s8 unk4B;
    s8 pad4C[0x50 - 0x4C];
    union X4_UnkObjLink link;
    union X4_UnkObjExt ext;
};
#endif
#ifndef X4_D_FixedMatrix2
#define X4_D_FixedMatrix2
struct X4_FixedMatrix2 {
    s16 m00, m01;
    s16 m10, m11;
};
#endif
#ifndef X4_D_u_short
#define X4_D_u_short
typedef unsigned short X4_u_short;
#endif
#ifndef X4_D_DR_ENV
#define X4_D_DR_ENV
typedef struct {
 X4_u_long tag;
 X4_u_long code[15];
} X4_DR_ENV;
#endif
#ifndef X4_D_DRAWENV
#define X4_D_DRAWENV
typedef struct {
 X4_RECT clip;
 short ofs[2];
 X4_RECT tw;
 X4_u_short tpage;
 X4_u_char dtd;
 X4_u_char dfe;
 X4_u_char isbg;
 X4_u_char r0, g0, b0;
 X4_DR_ENV dr_env;
} X4_DRAWENV;
#endif
#ifndef X4_D_DISPENV
#define X4_D_DISPENV
typedef struct {
 X4_RECT disp;
 X4_RECT screen;
 X4_u_char isinter;
 X4_u_char isrgb24;
 X4_u_char pad0, pad1;
} X4_DISPENV;
#endif
#ifndef X4_D_P_TAG
#define X4_D_P_TAG
typedef struct {
 unsigned addr: 24;
 unsigned len: 8;
 X4_u_char r0, g0, b0, code;
} X4_P_TAG;
#endif
#ifndef X4_D_OT_TYPE
#define X4_D_OT_TYPE
typedef u32 X4_OT_TYPE;
#endif
#ifndef X4_D_DrawOrderingTable
#define X4_D_DrawOrderingTable
struct X4_DrawOrderingTable {
    X4_OT_TYPE start;
    X4_OT_TYPE unk1;
    X4_OT_TYPE fade;
    X4_OT_TYPE unk3;
    X4_OT_TYPE mid;
    X4_OT_TYPE unk5[5];
    X4_OT_TYPE ui;
    X4_OT_TYPE end;
};
#endif
#ifndef X4_D_DrawInfo
#define X4_D_DrawInfo
struct X4_DrawInfo {
    X4_DISPENV dispenv;
    X4_DRAWENV drawenv;
    struct X4_DrawOrderingTable ordering_table;



};
#endif
#ifndef X4_D_BackgroundUnk3E
#define X4_D_BackgroundUnk3E
union X4_BackgroundUnk3E {
    u16 half;
    s8 bytes[2];
};
#endif
#ifndef X4_D_BackgroundObj
#define X4_D_BackgroundObj
struct X4_BackgroundObj {
    u8 unk0;
    u8 unk1;
    s8 unk2;
    s8 unk3;
    s8 unk4;
    u8 pad4[3];
    X4_f32 x_pos;
    X4_f32 y_pos;
    u8 pad10[4];
    X4_f32 unk14;
    X4_f32 unk18;
    s16 unk1C;
    s16 unk1E;
    s16 unk20;
    s16 unk22;
    s16 unk24;
    s16 unk26;
    s16 unk28;
    s16 unk2A;
    s16 unk2C;
    s16 unk2E;
    s16 unk30;
    s16 unk32;
    u16 unk34;
    s8 unk36;
    s8 unk37;
    u8 pad38[2];
    s8 unk3A;
    s8 unk3B;
    s8 unk3C;
    s8 unk3D;
    union X4_BackgroundUnk3E unk3E;
    u16 unk40;
    u16 unk42;
    s8 unk44;
    s8 unk45;
    s8 unk46;
    s8 unk47;
    s8 unk48;
    s8 unk49;
    u8 unk4A;
    u8 unk4B;
    u8 unk4C;
    u8 unk4D;
    u8 unk4E;
    s8 min_y;
    s8 max_y;
    s8 pad51[3];
};
#endif
#ifndef X4_D_Unk9
#define X4_D_Unk9
struct X4_Unk9 {
    u8 pad0[4];
    u8 unk4;
    u8 pad5[3];
    u32 unk8;
    u32 unkC;
    u8 padd[1];
    u32 unk14;
    u32 unk18;
    u16 unk1C;
    u16 unk1E;
    u16 unk20;
    u16 unk22;
    u16 unk24;
    u16 unk26;
    u16 unk28;
    u16 unk2A;
    s16 unk2C;
    s16 unk2E;
    s16 unk30;
    s16 unk32;
    u8 pad33[19];
    s8 unk47;
    s8 unk48;
    s8 unk49;
};
#endif
#ifndef X4_D_StageObjectRecord
#define X4_D_StageObjectRecord
struct X4_StageObjectRecord {
    u8 flags, id, subtype, object_type;
    s16 x, y;
};
#endif
#ifndef X4_D_arg_u8
#define X4_D_arg_u8
typedef s32 X4_arg_u8;
#endif
#ifndef X4_D_MovingObj
#define X4_D_MovingObj
struct X4_MovingObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref; s8 bg_offset; u8 unk15; u8 unk16; u8 unk17; X4_f32 unk18; X4_f32 unk1C; X4_f32 x_vel; X4_f32 y_vel;
};
#endif
#ifndef X4_D_BarObj
#define X4_D_BarObj
struct X4_BarObj {
    s8 : 8;
    s8 : 8;
    s8 unk2;
    s8 : 8;
    s8 state;
    s8 unk5;
    s8 unk6;
    s8 pad7;
    s32 x_pos;
    s8 padC[8];
    s8 unk14;
    s8 : 8;
    u8 unk16[8];
    s16 : 16;
    u8 unk20;
    u8 unk21;
    u8 unk22;
    s8 : 8;
    s8 : 8;
    u8 unk25;
    s8 pad26[0x28 - 0x26];
    s32 unk28;
    s32 unk2C;
    s32 unk30;
};
#endif
#ifndef X4_D_PlayerCollision
#define X4_D_PlayerCollision
enum X4_PlayerCollision {
    PLAYER_COLLIDE_RIGHT = 0x1,
    PLAYER_COLLIDE_LEFT = 0x2,
    PLAYER_COLLIDE_CEILING = 0x4,
    PLAYER_COLLIDE_GROUND = 0x8,
};
#endif
#ifndef X4_D_PlayerInput
#define X4_D_PlayerInput
enum X4_PlayerInput {
    PLAYER_INPUT_RIGHT = 0x1,
    PLAYER_INPUT_LEFT = 0x2,
    PLAYER_INPUT_UP = 0x4,
    PLAYER_INPUT_DOWN = 0x8,
    PLAYER_INPUT_SHOOT = 0x10,
    PLAYER_INPUT_SPECIAL = 0x20,
    PLAYER_INPUT_GIGA = 0x40,
    PLAYER_INPUT_JUMP = 0x80,
    PLAYER_INPUT_DASH = 0x100,
    PLAYER_INPUT_NEXT_WEAPON = 0x200,
    PLAYER_INPUT_PREVIOUS_WEAPON = 0x400,
};
#endif
#ifndef X4_D_PlayerAction
#define X4_D_PlayerAction
enum X4_PlayerAction {
    PLAYER_BEAM_IN,
    PLAYER_BEAM_OUT,
    PLAYER_IDLE,
    PLAYER_WALK_START,
    PLAYER_WALK,
    PLAYER_SETTLE,
    PLAYER_JUMP,
    PLAYER_FALL,
    PLAYER_LAND,
    PLAYER_WALL_CLING,
    PLAYER_WALL_JUMP,
    PLAYER_WALL_SLIDE,
    PLAYER_DASH,
    PLAYER_AIR_DASH,
    PLAYER_LADDER_TRANSITION,
    PLAYER_LADDER_UP,
    PLAYER_LADDER_DOWN,
    PLAYER_HURT,
    PLAYER_RIDE,
    PLAYER_CAPSULE,
    PLAYER_SCRIPT_WAIT,
    PLAYER_SCRIPT_WALK,
    PLAYER_SCRIPT_VANISH,
    PLAYER_SCRIPT_JUMP,
    PLAYER_SCRIPT_VICTORY,
    PLAYER_STAGE_CLEAR,
    PLAYER_LADDER_SHOOT = 0x20,
    PLAYER_HOVER,
    PLAYER_NOVA_STRIKE,
    PLAYER_SOUL_BODY,
    PLAYER_SOUL_BODY_CLONE,
    PLAYER_SOUL_BODY_VANISH,
    PLAYER_WEAPON_POSE,
    PLAYER_RISING_FIRE,
    PLAYER_RISING_FIRE_CHARGED,
    PLAYER_ZERO_SABER = 0x30,
    PLAYER_ZERO_JUMP_SLASH,
    PLAYER_ZERO_FALL_SLASH,
    PLAYER_ZERO_LADDER_SLASH,
    PLAYER_ZERO_WALL_SLASH,
    PLAYER_ZERO_RAIJINGEKI,
    PLAYER_ZERO_HYOURETSUZAN,
    PLAYER_ZERO_SPIN_JUMP_SLASH,
    PLAYER_ZERO_SPIN_FALL_SLASH,
    PLAYER_ZERO_RYUENJIN,
    PLAYER_ZERO_RAKUHOUHA,
    PLAYER_ZERO_SHIPPUUGA,
};
#endif
#ifndef X4_D_PLAYER_CHARGE_FULL
#define X4_D_PLAYER_CHARGE_FULL
enum {
    PLAYER_CHARGE_NONE,
    PLAYER_CHARGE_PARTIAL,
    PLAYER_CHARGE_FULL,
};
#endif
#ifndef X4_D_Main76HandlerTable
#define X4_D_Main76HandlerTable
struct X4_Main76HandlerTable {
    void (*funcs[7])(void*);
};
#endif
#ifndef X4_D_VisualAttachmentOffset
#define X4_D_VisualAttachmentOffset
struct X4_VisualAttachmentOffset {
    s16 x, y;
};
#endif
#ifndef X4_D_ReadyLineExt
#define X4_D_ReadyLineExt
struct X4_ReadyLineExt {
    X4_f32 x_vel;
    X4_f32 y_vel;
    X4_f32 x_accel;
    X4_f32 y_accel;
};
#endif
#ifndef X4_D_SearchLightMotion
#define X4_D_SearchLightMotion
struct X4_SearchLightMotion {
    s32 velocity;
    s32 acceleration;
    s32 vertical_velocity;
    s32 vertical_acceleration;
};
#endif
#ifndef X4_D_QuadUnkExt
#define X4_D_QuadUnkExt
struct X4_QuadUnkExt {
    u16 unk38;
};
#endif
#ifndef X4_D_TitleQuadExt
#define X4_D_TitleQuadExt
struct X4_TitleQuadExt {
    u16 unk38;
    u8 unk3A[4];
    u8 unk3E[4];
    u8 unk42;
    u8 unk43;
};
#endif
#ifndef X4_D_Quad4Ext
#define X4_D_Quad4Ext
struct X4_Quad4Ext {
    u8 unk38;
    u8 unk39;
    u8 timer;
};
#endif
#ifndef X4_D_QuadScale
#define X4_D_QuadScale
union X4_QuadScale {
    u16 value;
    struct {
        u8 fraction;
        u8 integer;
    } bytes;
};
#endif
#ifndef X4_D_Quad2Ext
#define X4_D_Quad2Ext
struct X4_Quad2Ext {
    const s32* vertices;
    union X4_QuadScale x_scale;
    union X4_QuadScale y_scale;
    u8 direction[2];
};
#endif
#ifndef X4_D_QuadMotionData
#define X4_D_QuadMotionData
struct X4_QuadMotionData {
    u16 vertex[4];
    s8 speed[4];
};
#endif
#ifndef X4_D_QuadUnkExt3
#define X4_D_QuadUnkExt3
struct X4_QuadUnkExt3 {
    u8 unk38;
};
#endif
#ifndef X4_D_Quad5Ext
#define X4_D_Quad5Ext
struct X4_Quad5Ext {
    s32* data;
    u16 scale;
    s16 update_timer;
    u16 index;
};
#endif
#ifndef X4_D_Quad10Ext
#define X4_D_Quad10Ext
struct X4_Quad10Ext {
    s32 counter;
    s32 x_step;
    s32 y_step;
    u8 progress;
    u8 history[3];
};
#endif
#ifndef X4_D_QuadUnkExt4
#define X4_D_QuadUnkExt4
struct X4_QuadUnkExt4 {
    s32 : 32;
    u16 unk3C;
};
#endif
#ifndef X4_D_Quad1Ext
#define X4_D_Quad1Ext
struct X4_Quad1Ext {
    u8 settled[4];
    u8 region[4];
    u16 steps;
    u8 unk42;
    u8 delay;
};
#endif
#ifndef X4_D_QuadExt
#define X4_D_QuadExt
union X4_QuadExt {
    struct X4_Quad1Ext quad_1;
    struct X4_ReadyLineExt ready_line;
    struct X4_SearchLightMotion search_light;
    struct X4_QuadUnkExt unk_ext;
    struct X4_TitleQuadExt title_quad;
    struct X4_Quad4Ext quad_4;
    struct X4_Quad5Ext quad_5;
    struct X4_Quad2Ext quad_2;
    struct X4_QuadUnkExt3 unk_ext3;
    struct X4_QuadUnkExt4 unk_ext4;
    struct X4_Quad10Ext quad_10;
    u32 unk38;
};
#endif
#ifndef X4_D_SearchLightRuntime
#define X4_D_SearchLightRuntime
struct X4_SearchLightRuntime {
    s32 x_accumulator;
    s32 y_accumulator;
    u16 pause_timer;
    s16 extent;
    s32 base_speed;
};
#endif
#ifndef X4_D_Quad06Runtime
#define X4_D_Quad06Runtime
struct X4_Quad06Runtime {
    s32 x_accumulator;
    s32 y_accumulator;
    s32 acceleration;
    s32 base_speed;
};
#endif
#ifndef X4_D_ReadyLineRuntime
#define X4_D_ReadyLineRuntime
struct X4_ReadyLineRuntime {
    u8 directions[4];
    u8 crossed[4];
    u16 interpolation_frames;
    s16 delay;
    u8 converging;
    u8 initialized;
    u8 alignment[2];
};
#endif
#ifndef X4_D_QuadRuntime
#define X4_D_QuadRuntime
union X4_QuadRuntime {
    struct {
        u8 unk48;
        s8 pad_[3];
        s8 unk4C;
        s8 unk4D;
        s8 unk4E;
        s8 unk4F;
        u16 unk50;
        s16 unk52;
        s8 unk54;
        s8 unk55;
        u8 pad56[2];
    } legacy;
    struct X4_SearchLightRuntime search_light;
    struct X4_Quad06Runtime quad_06;
    struct X4_ReadyLineRuntime ready_line;
};
#endif
#ifndef X4_D_QuadLink
#define X4_D_QuadLink
union X4_QuadLink {
    struct X4_EffectObj* owner;
    u16 direction;
};
#endif
#ifndef X4_D_QuadVertex
#define X4_D_QuadVertex
struct X4_QuadVertex {
    X4_f32 x;
    X4_f32 y;
};
#endif
#ifndef X4_D_QuadObj
#define X4_D_QuadObj
struct X4_QuadObj {
    s8 active; s8 id; s8 unk2; s8 on_screen; s8 state; s8 unk5; s8 unk6; s8 unk7; X4_f32 x_pos; X4_f32 y_pos; void* backref;
    struct X4_QuadVertex vertices[4];
    u16 unk34;
    s8 unk36;
    s8 bg_offset;
    union X4_QuadExt ext;
    union X4_QuadRuntime runtime;
    union X4_QuadLink link;
    struct X4_PlayerObj* unk5C;
};
#endif
#ifndef X4_D_quad
#define X4_D_quad
typedef struct X4__quad { long val[2]; } X4_quad;
#endif
#ifndef X4_D_MenuTextureData
#define X4_D_MenuTextureData
struct X4_MenuTextureData {
    u32 texture[96];





    s16 bounds[8];
};
#endif

#endif /* MMX6_X4_H */
